### ISSUE TITLE
Neovim doesn't respond when trying to open file opened by another instance

### ISSUE THREAD

**Issue by 10110111** [equalsraf/neovim-qt#292] opened 2017-06-14 10:43 UTC
To reproduce in bash:
1. Run `nvim testfile`, then stop it by Ctrl+Z
2. Run `nvim-qt testfile`
3. Wait several seconds while the GUI hang
4. See the console output:
```
Request 1 timed out: 44
Neovim fatal error "Neovim is taking too long to respond"
```
and the same message with a _Retry_ button in the X window.

If, instead of `nvim-qt`, you launch `nvim` in step 2, you'll see NVim's prompt of what to do with the already present swap file:
```
Swap file "~/.vim/swap//%tmp%testfile.swp" already exists!
[O]pen Read-Only, (E)dit anyway, (R)ecover, (Q)uit, (A)bort:
```

**Comment by equalsraf** [comment] 2017-06-14 11:52
its a known issue with the GUI startup https://github.com/neovim/neovim/issues/3901

Closing as a duplicate of https://github.com/equalsraf/neovim-qt/issues/78

**Closed by equalsraf** 2017-06-14 11:52 UTC
