### ISSUE TITLE
Got two cursors when in :terminal

### ISSUE THREAD

**Issue by bohrshaw** [equalsraf/neovim-qt#291] opened 2017-06-05 12:40 UTC
I.E. the cursor in Normal Mode doesn't disappear when the cursor in Terminal Mode appears.
This happens when doing `nvim-qt.exe --server 192.168.81.2:8044`, then `:term`.

**Comment by YorickPeterse** [comment] 2019-03-23 01:52
I'm also running into this issue. It happens regardless of using a remote or local neovim instance:

![Screenshot from 2019-03-23 02-52-30](https://user-images.githubusercontent.com/86065/54860174-b868b580-4d16-11e9-8c22-4f073e850f13.png)

**Comment by equalsraf** [comment] 2019-03-23 14:05
~~Not seeing this one here, there is some oddity on around the terminal cursor because of https://github.com/equalsraf/neovim-qt/issues/145 but it would not explain this.~~ I can see it, my second cursor was hiding in a corner.

Based on the screen shot it would seem we did not redraw the cursor previous position when we should. Wild guess -- because the terminal is drawing its own cursor, we might have to do something when the switching to terminal mode e.g. clearing the cursor.

Case and point, disabling the cursor drawing [here](https://github.com/equalsraf/neovim-qt/blob/1187a30c019ae7b754eab92a7552ef2d70fe66bc/src/gui/shell.cpp#L830) does not prevent the cursor from showing up in the terminal. So it seems that when switching to terminal mode we need to update the previous cursor position and disable cursor drawing.

**Comment by BYK** [comment] 2019-08-28 10:33
I'm also having this issue (Win 10 + Alacritty) and would love to help resolve it. Any pointers so maybe I can submit a PR?

**Comment by equalsraf** [comment] 2019-08-28 17:22
@BYK this is actually fixed in the latest release :D can you check with the latest binaries?

This commit fixed it https://github.com/equalsraf/neovim-qt/commit/0360b330c831aa92c867c581a44cbb321c9c43b0

**Comment by YorickPeterse** [comment] 2019-08-29 15:48
I can confirm this problem has been fixed on v0.2.13. Thanks! :tada: :+1:

**Comment by BYK** [comment] 2019-08-29 16:42
@equalsraf oh sorry, I got confused and thought this was neovim itself :D Was this supposed to be fixed in Neovim itself?

**Comment by equalsraf** [comment] 2019-08-29 17:09
> @equalsraf oh sorry, I got confused and thought this was neovim itself :D Was this supposed to be fixed in Neovim itself?

No this was entirely my fault :)

**Closed by equalsraf** 2019-08-29 17:09 UTC

**Comment by BYK** [comment] 2019-08-29 17:18
>No this was entirely my fault :)

Hahaha, I'm guessing I need a fix in Alacritty itself then :D Thanks a lot!
