### ISSUE TITLE
<C-Space> Not Recognized

### ISSUE THREAD

**Issue by ewhac** [equalsraf/neovim-qt#931] opened 2021-09-14 08:06 UTC
In the giant pile of suggested key mappings provided with coc.nvim, one uses CTRL-space to trigger the display of completion suggestions.  This mapping does not work inside neovim-qt.  Indeed, neovim-qt doesn't appear to see \<C-space\> at all.

To reproduce: Enter Insert mode, then press \<C-V\> to insert the next literal character.  Then press \<C-space\>.  Nothing will happen.  Doing the same thing from within nvim running on a terminal (rxvt) will insert the string "\<C-Space\>".

**Comment by jgehrig** [comment] 2021-09-21 03:09
This looks like a duplicate of #917 56ad7e54a27f1bed2fcbe9e3bf22f9394360c722. Marking as closed.



This issue should be fixed on the [latest build](https://github.com/equalsraf/neovim-qt/actions/runs/1186992983) from `master`. 

If you still have issues, please let me know and I will investigate further.

**Closed by jgehrig** 2021-09-21 03:09 UTC
