### ISSUE TITLE
build fails on GCC 4.8.4/Ubuntu 14.04

### ISSUE THREAD

**Issue by turtleDev** [equalsraf/neovim-qt#146] opened 2016-06-22 06:15 UTC
compiler: gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
system: Linux 3.16.0-30-generic  # 40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 

I can't seem to build neovim-qt. I believe I have all the required dependencies. Here's the error message I get when the build fails:
```
Scanning dependencies of target tst_shell
[ 98%] Building CXX object test/CMakeFiles/tst_shell.dir/tst_shell.cpp.o
/.../build/neovim-qt/test/tst_shell.cpp: In member function ‘void NeovimQt::Test::checkStartVars(NeovimQt::NeovimConnector*)’:
/.../build/neovim-qt/test/tst_shell.cpp:78:60: error: no matching function for call to ‘QSignalSpy::QSignalSpy(NeovimQt::Neovim*&, void (NeovimQt::Neovim::*)(QVariant))’
    QSignalSpy onVar(nvim, &NeovimQt::Neovim::on_vim_get_var);
                                                            ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [test/CMakeFiles/tst_shell.dir/tst_shell.cpp.o] Error 1
make[1]: *** [test/CMakeFiles/tst_shell.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by equalsraf** [comment] 2016-06-23 20:56
This is a duplicate of https://github.com/equalsraf/neovim-qt/issues/137, can you test with https://github.com/equalsraf/neovim-qt/pull/138?

**Comment by turtleDev** [comment] 2016-06-24 05:20
@equalsraf #138 fixed the issue. Thanks!

**Comment by turtleDev** [comment] 2016-06-24 05:38
however, I get these error messages when I run nvim (though it still works fine)

```
Unknown Neovim function "Object vim_call_function(String fname, Array args) !fail" 
Unknown Neovim function "Dictionary vim_get_color_map()" 
Unknown Neovim function "Array vim_get_api_info()" 
```

**Comment by equalsraf** [comment] 2016-06-30 07:57
The fix has been merged into the master branch. As for the error messages you mentioned they are normal and are only displayed in Debug builds.

**Closed by equalsraf** 2016-06-30 07:57 UTC
