### ISSUE TITLE
"nvim-qt --help" crashes if it can't connect to $DISPLAY

### ISSUE THREAD

**Issue by jamessan** [equalsraf/neovim-qt#707] opened 2020-06-18 02:00 UTC
Since 847f0271f2af61a35e8676e069a2e8b31a527760, running `env -u DISPLAY nvim-qt --help` crashes.

I noticed this because the Debian packaging uses `nvim-qt --help` (via help2man) to create a man page.  In the build, there's no `$DISPLAY` unless one is specifically setup so this started crashing with v0.2.16.

**Comment by jgehrig** [comment] 2020-06-19 04:52
@jamessan Thanks for finding the root cause!

@equalsraf Since I introduced this, I am happy to write a fix.

Interesting bug... The `QApplication` constructor causes the crash. We will need to use `QCoreApplication`, unfortunately Qt makes sharing code between the two difficult.

**Comment by jgehrig** [comment] 2020-06-19 05:10
Also worth noting...

The behavior is common to most Qt applications. All of my KDE applications crash in the same manner:
```
$ env -u DISPLAY dolphin --help

qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-org.kde.kwin.qpa, minimal, offscreen, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted (core dumped)
```

This seems like an upstream bug in Qt. However, this is also a regression and bad behavior...

**Comment by jgehrig** [comment] 2020-07-09 17:58
Confirmed `env -u DISPLAY nvim-qt --help` is working in the latest release. Closing.

**Closed by jgehrig** 2020-07-09 17:58 UTC
