### ISSUE TITLE
Can't use '~' with the bépo keyboard disposition

### ISSUE THREAD

**Issue by franckspike** [equalsraf/neovim-qt#864] opened 2021-06-02 13:20 UTC
neovim-qt version v0.2.16.0 under Windows 10 x64
(still present in 0.2.16.1)

### Steps to reproduce

using bépo keyboard disposition https://bepo.fr/wiki/Accueil

nvim-qt -- -u NORC

try inserting the ~ character: done using a dead key combination: AltGr-; AltGr-;
 ; here represents the qwerty (physical) ; key
thinking in the bépo disposition, the ; physical key gives n so the bépo combination is rather named: AltGr-n AltGr-n
(just press AltGr-; AltGr-; on the physical keyboard)

the same happens on a : command or / search

note that nvim works properly, only nvim-qt has this problem

I'm pretty sure other dead key combinations should also cause such a problem

### Actual behaviour

~ won't appear is it should
doing the combination 3 times types something weird and is not a simple ~ character

### Expected behaviour

this combination twice should just give a single ~ character

### Note

This might be related to #720

**Comment by jgehrig** [comment] 2021-06-02 14:19
@franckspike

Thanks for the bug report! We can get this fixed...

I'm not familiar with the bépo keyboard layout. Can you help with testing?

We'll need some debug output of the specific key events you're using.

I've created a build for you to test with at #865. Please exercise some of these keys, describe what you've pressed, and upload the created log files. Once the AppVeyor build completes, you should be able to download `neovim.zip`. Either build works, MinGW or MSVC.

**Download Link:**
https://ci.appveyor.com/project/equalsraf/neovim-qt/builds/39430605/job/964ppnmc88auatjk/artifacts
```
set NVIM_QT_LOG=DebugOutput.txt
nvim-qt.exe
```

**Optional Info:**
https://github.com/equalsraf/neovim-qt/wiki#i-cant-see-debug-messages-in-windows
https://github.com/equalsraf/neovim-qt/wiki/Windows-AppVeyor-Builds

**Comment by franckspike** [comment] 2021-06-02 15:13
I believe the NVIM_QT_LOG env var is not taken into account, it won't create the log file, nor with an absolute path, with / or \, even when starting (the right nvim-qt) with -- -u NORC

**Comment by jgehrig** [comment] 2021-06-02 15:24
> I believe the NVIM_QT_LOG env var is not taken into account

Doh! This is my fault...

That feature is only enabled with `Debug` builds, and I forgot AppVeyor generates `Release` builds.

Usually, folks build `neovim-qt` from source to get this info. However, the builds on Windows are difficult to configure.

I will quickly poke AppVeyor and generate a new Windows `Debug` build.

**Comment by franckspike** [comment] 2021-06-02 15:30
I am a developer, I could configure it soon, but I must concentrate on my work first :-)

**Comment by jgehrig** [comment] 2021-06-03 14:30
@franckspike 

Excellent, good to know :+1: 

New AppVeyor `Debug` build:
https://ci.appveyor.com/project/equalsraf/neovim-qt/builds/39432218/job/8niplukxt2j88ubh/artifacts

You should be able to build on Windows if needed, but even I find this slow and cumbersome

I also may have discovered an Debug vs Release MSVC issue... Interesting.

**Comment by franckspike** [comment] 2021-06-03 16:27
QKeyEvent ev: QKeyEvent(KeyPress, Key_QuoteDbl, text="1")
   "1"
QKeyEvent ev: QKeyEvent(KeyPress, Key_CapsLock)
   ""

then here's the AltGr-n AltGr-n

QKeyEvent ev: QKeyEvent(KeyPress, Key_Control, ControlModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Alt, ControlModifier|AltModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Control, ControlModifier|AltModifier)
   ""

followed by [enter]

QKeyEvent ev: QKeyEvent(KeyPress, Key_Return, text="?")
   "<Enter>"
QKeyEvent ev: QKeyEvent(KeyPress, 0, text="\r")
   "\u0000"

then again (but 3 times)  AltGr-n AltGr-n AltGr-n
(it's normally 2 times)

QKeyEvent ev: QKeyEvent(KeyPress, Key_Control, ControlModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Alt, ControlModifier|AltModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_AsciiTilde, ControlModifier|AltModifier, text="?")
   "?"
QKeyEvent ev: QKeyEvent(KeyPress, 0, ControlModifier|AltModifier, text="~")
   "~"

then followed again by [enter]

QKeyEvent ev: QKeyEvent(KeyPress, Key_Return, text="\r")
   "<Enter>"

**Comment by jgehrig** [comment] 2021-06-03 16:44
I hoped I could easily spot what is going wrong... However, I'm not familiar enough with this layout to understand what the expected behavior should be from these logs.

When you have some time, can you put together a table like the following:

Key Combination | Expected | Obtained | Result | QKeyEvent
-- | -- | -- | -- | --
Alt + ?? | ? | ? | OK / FAIL | QKeyEvent ev: ...

Does bépo have "dead" key events that impact future input?

Something like:
1. Alt + Key. Does nothing now, adds accent to next key
2. Key N. Inputs N + accent from previous keystroke

Hopefully we don't have to introduce state into the input layer. Currently, all input layers functions are pure; no side-effects or state.

**Comment by franckspike** [comment] 2021-06-03 16:51
Autohotkey gives me this

A2  01D	 	d	10.16	LControl       	
A5  138	 	d	0.00	RAlt           	
A2  01D	 	d	0.25	LControl       	
A5  138	 	d	0.00	RAlt           	
4E  027	 	d	0.01	n              	
4E  027	 	u	0.14	n              	
4E  027	 	d	0.14	n              	
4E  027	 	u	0.13	n              	
A2  01D	 	u	0.08	LControl       	
A5  138	 	u	0.00	RAlt

**Comment by franckspike** [comment] 2021-06-03 18:07
the same happens with the ^ dead key followed by space to display "^" on french qwerty

**Comment by jgehrig** [comment] 2021-06-03 18:50
Glad to hear you've got a workaround! :+1: 

It would still be nice to get the information from the table above. We've got a bug in the `neovim-qt` input layer that would be nice to fix.

**Comment by franckspike** [comment] 2021-06-03 19:04
Key Combination | Expected | Obtained | Result | QKeyEvent
-- | -- | -- | -- | --
Ctrl + Alt + n, Ctrl + Alt + n | ~ | nothing | OK / FAIL | QKeyEvent ev: (1)
Ctrl + Alt + n, Ctrl + Alt + n, Ctrl + Alt + n | ~ | nothing | OK / FAIL | QKeyEvent ev: (2)

(1)
QKeyEvent ev: QKeyEvent(KeyPress, Key_Control, ControlModifier)
""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Alt, ControlModifier|AltModifier)
""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Control, ControlModifier|AltModifier)
""

(2)
QKeyEvent ev: QKeyEvent(KeyPress, Key_Control, ControlModifier)
""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Alt, ControlModifier|AltModifier)
""
QKeyEvent ev: QKeyEvent(KeyPress, Key_AsciiTilde, ControlModifier|AltModifier, text="?")
"?"
QKeyEvent ev: QKeyEvent(KeyPress, 0, ControlModifier|AltModifier, text="~")
"~"


the 2nd is more like a hack not to be done
and the 1st do not receive the Key_AsciiTilde or "\~" so that the good way could work…

**Comment by jgehrig** [comment] 2021-06-04 15:09
Interesting, this looks like it might be a Qt bug? Do you have another Qt based app to test with?

Usually in these cases, we see a valid `text` field and for some reason the input layer has decided to overwrite or apply modifiers to it. Ex) `QKeyEvent(KeyPress, Key_Control, AltModifier, text="~")` becomes `<A-~>`

This input is along the lines of what I would expect to see (without workaround):
`QKeyEvent ev: QKeyEvent(KeyPress, 0, ControlModifier|AltModifier, text="~")`

For `Run 1` there isn't enough information for us to parse. I don't see a way to reliably pull `~` out of that input.

For `Run 2`, I don't think we want to parse this, since you've applied your workaround with AutoHotkey. Although, clever workaround.

**Comment by franckspike** [comment] 2021-06-04 15:41
Ok we need to start over again !!
I was doing the wrong key presses (because I was trying anything in nvim-qt…)

the key press for ~ is AltGr-n, Space
the key press for ^ is AltGr-^, Space

here are the logs for them

WOW we got the solution !!!  (GuitarPro (Qt), it works)

------
QKeyEvent ev: QKeyEvent(KeyPress, Key_Control, ControlModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Alt, ControlModifier|AltModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Space, text="\~")   <---- for ~
   "<Space>"
-----
QKeyEvent ev: QKeyEvent(KeyPress, Key_Space, text="\^")    <----- for ^
   "<Space>"
------

-----
QKeyEvent ev: QKeyEvent(KeyPress, Key_Space, text=" ")    <----- for " "
   "<Space>"
------

As a general rule maybe when receiving Key_Space, _text_ attribute should always be used !?

**Comment by jgehrig** [comment] 2021-06-04 16:42
> QKeyEvent ev: QKeyEvent(KeyPress, Key_Space, text="~") <---- for ~

Woohoo!

Okay, this looks fixable...

> As a general rule maybe when receiving Key_Space, text attribute should always be used !?

Yes, the solution will be something like this. The first step is to write test coverage, then tweak the logic carefully.

---

Can you (easily) test these same scenarios on MacOS or Linux?

If not, no problem. We will just fix what we can easily test.

For other layouts with multi-step input, the behavior is usually platform specific. This might not even be an issue on Mac/Linux...

**Comment by franckspike** [comment] 2021-06-04 16:51
I don't easily have access to Linux other than my no UI setup on WSL 2 (and no MacOS) :-/
I wish I was not so overloaded with my job and other things…
I'm happy we could finally find a solution :-)

**Comment by jgehrig** [comment] 2021-06-04 17:03
> I don't easily have access to Linux other than my no UI setup on WSL 2 (and no MacOS) :-/

Not a problem at! Thank you for all of your help so far.

I'll let you know when I have a finalized solution for testing.

**Comment by franckspike** [comment] 2021-06-04 18:01
Thank you very much!

**Comment by jgehrig** [comment] 2021-06-05 01:04
I just pushed a fix for this scenario. Can you quickly test it?

https://ci.appveyor.com/project/equalsraf/neovim-qt/builds/39471940/job/gmj7akxhcs4g4t3t/artifacts

Another scenario to consider is Shift/Alt/Control interaction.

For example:
1. In `Insert` mode, press Ctrl + V
2. CTRL + ALT + N
3. Shift/Alt/Control + Space
4. What is the input?
  a. Terminal: What appears? <S-~>? ~?
  b. Neovim-Qt: What is the QKeyEvent?

Hopefully this works for you! :)

**Comment by franckspike** [comment] 2021-06-05 15:19
I can and will have a look at it on Monday!

**Comment by franckspike** [comment] 2021-06-07 12:45
This build fixes perfectly the current issue :-)

By the way, I just found out I have Qt built on my system (5.11.1 msvc2017_64)…
Maybe I'm not too far from building nvim-qt !?

**Comment by franckspike** [comment] 2021-06-07 12:51
Oh, and how can I paste "* or "+ in /search and :command ?

**Comment by jgehrig** [comment] 2021-06-07 17:18
I've always added a `Shift + Insert` map in my vimrc:
```
" Shift Insert Paste (Command Mode, Insert Mode)
cmap <S-Insert> <C-R>+
imap <S-Insert> <C-R>+
```

You should be able to manually paste from any buffer with `Ctrl + R` followed by the buffer `*`, `+`, etc.

> Maybe I'm not too far from building nvim-qt !?

I bet you can figure it out!

I always have trouble getting the settings from `PATH` correct on Windows. It's always slightly different depending on the machine. After it is built, sometimes you will also need to play around with `PATH` so the correct DLLs are available at runtime.

I only avoid asking folks to build on Windows because I find it tedious myself. It is also difficult to point to a clear set of instructions that works every time. Usually it is faster for everyone to provide the pre-built zip :)

**Comment by franckspike** [comment] 2021-06-07 17:36
I'm having Qt 5.11.1 but I heard 6 is out, I haven't looked at nvim-qt documentation yet, I think could also need this project so I can embed vim in other apps or controls or something alike… So I'll build it soon

by the way, is it really needed to fork the project to make pull requests ?

usually I just copy the required DLLs in the output directory (beside the .exe) (both on dev and deploy), but I don't like this Windows way lol… posix is better because of sharing…

**Comment by jgehrig** [comment] 2021-06-17 19:15
I'm going to merge this fix soon. I assume  your testing went well, and we're ready for check-in.

--- 

Sorry, I missed your comments.

> embed vim in other apps or controls or something alike

Cool!

It was designed to be used as a library in this manner, but this is not common. Feel free to open issues or PRs.

> by the way, is it really needed to fork the project to make pull requests ?

Yes, that is the GitHub way... It isn't a true "fork", just a GitHub copy you are free to modify and commit to.

I'm not a fan of Git (blasphemy, I know). The tool isn't very user-friendly, and everyone uses DVCS as a centralized VCS. Perplexing!

> posix is better because of sharing (with versions)…

Yes! Windows is a mess... Especially shared libs (DLLs) and package management.

**Comment by franckspike** [comment] 2021-06-21 16:18
Yes, testing when well! Thank you very much!

I'll have a look at this project

François

**Comment by yurickgomes** [comment] 2021-06-23 19:45
@jgehrig i was facing the same issue with my brazilian keyboard and the build: https://github.com/equalsraf/neovim-qt/issues/864#issuecomment-855159529 solved the problem. Thanks!

**Comment by jgehrig** [comment] 2021-06-24 21:14
Merged! Closing this issue.

@yurickgomes

I'm glad to hear this also fixed your Brazilian layout input issues!

If you can easily send along `QKeyEvent` input, it'd be great to add some test coverage... If not, no worries.

```
// Uncomment for key input debugging and unit test writing.
// qDebug() << "QKeyEvent ev:" << ev;
// qDebug() << "  " << inp;
```

**Closed by jgehrig** 2021-06-24 21:14 UTC

**Comment by yurickgomes** [comment] 2021-06-24 22:00
@jgehrig here are the logs using my ptBR keyboard http://kbdlayout.info/KBDBR/
```
QKeyEvent ev: QKeyEvent(KeyPress, Key_I, text="i")
   "i"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Space, text="~")
   "~"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Space, text="`")
   "`"
QKeyEvent ev: QKeyEvent(KeyPress, Key_A, text="ã")
   "ã"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_A, text="à")
   "à"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Ccedilla, text="ç")
   "ç"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Apostrophe, text="'")
   "'"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_QuoteDbl, ShiftModifier, text="\"")
   "\""
QKeyEvent ev: QKeyEvent(KeyPress, Key_E, text="é")
   "é"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_E, text="ê")
   "ê"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_A, text="â")
   "â"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Ccedilla, ShiftModifier, text="Ç")
   "Ç"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_A, ShiftModifier, text="Á")
   "Á"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_E, ShiftModifier, text="É")
   "É"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_E, ShiftModifier, text="Ê")
   "Ê"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_O, ShiftModifier, text="Ó")
   "Ó"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Escape, text="\u001B")
   "<Esc>"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Ccedilla, ShiftModifier, text="Ç")
   "Ç"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Q, text="q")
   "q"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Exclam, ShiftModifier, text="!")
   "!"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Return, text="\r")
   "<Enter>"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Escape, text="\u001B")
   "<Esc>"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Colon, ShiftModifier, text=":")
   ":"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Q, text="q")
   "q"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Exclam, ShiftModifier, text="!")
   "!"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Return, text="\r")
   "<Enter>"
Neovim requested a GUI close```
