### ISSUE TITLE
Cannot map . (dot) / windows

### ISSUE THREAD

**Issue by archpastor** [equalsraf/neovim-qt#920] opened 2021-08-16 14:49 UTC
`map . <smth>` has no effect and works as default.
Tested with: windows7/10, nvim-qt bundled with nvim 0.5.0/0.6.0 ([5a111c1](https://github.com/neovim/neovim/commit/5a111c1b02bbfbc2b42df11d7205153be0893dff)), last pre-built windows binary ([56ad7e5](https://github.com/equalsraf/neovim-qt/commit/56ad7e54a27f1bed2fcbe9e3bf22f9394360c722)).

**Comment by justinmk** [comment] 2021-08-16 14:54
what is the result of

    :verbose map .

when are you setting the map? provide full steps.

**Comment by Archpastor** [comment] 2021-08-16 15:06
With empty init.vim for clarity:
`:verbose map .`
`No mapping found`
`:map . j`
`:verbose map .`
`  .            j`
![RCsEzXvV_3Q](https://user-images.githubusercontent.com/32925947/129585619-0494596f-95dc-42ad-a718-e6654c4cd2ad.jpg)
But it still works as default .

**Comment by jgehrig** [comment] 2021-08-16 16:49
@Archpastor 

Do you see the same issues in `nvim` and `nvim-qt`?

What do you observe that suggests this is not working?

I cannot reproduce the issue `nvim-qt` (master) and `nvim` (v0.5.0).

1. `100 o <Esc>`
2. `gg`
3. `:map . j`
4. `.` (Cursor moves down)

![No-Repro-Map-Dot](https://user-images.githubusercontent.com/11207308/129599771-4c5f26d9-9322-4e46-abdc-e38fa003cd40.gif)

**Comment by Archpastor** [comment] 2021-08-16 17:40
@jgehrig
No, this behavior is observed only in `nvim-qt.exe`
I repeat your steps with my case on gif (`win10`, `nvim 0.5.0`).
The same is on second device (`win7`) and with other versions (last `nvim nightly 0.6.0`; last `nvim-qt` [56ad7e5](https://github.com/equalsraf/neovim-qt/commit/56ad7e54a27f1bed2fcbe9e3bf22f9394360c722)).
![Animation](https://user-images.githubusercontent.com/32925947/129605214-e00805b8-9f51-478b-965e-5ab2ff6f6b9b.gif)

**Comment by jgehrig** [comment] 2021-08-17 02:03
Very strange... It looks like we're doing the same steps, but I cannot reproduce the issue.

You're on Windows and I'm on Linux, so I tried these steps on one of my Windows machines. Worked fine.

I also tried downgrading to `v0.2.16.1`. Worked fine.

---

Are you running with an empty configuration `nvim-qt -- -u NONE`?

Are you using a non-english keyboard layout? AutoHotkey?

Can you think of anything that is unique about your machines?

Does `i` `Ctrl + V` `.` output something other than `.`?

**Comment by archpastor** [comment] 2021-08-17 04:17
Oh, you right. It seems the part of the problem is really with ahk.
I'm very confused, it does not cause such problems with all other symbols. All my non-letter bindings work through one function, the dot has nothing special.

I tried some variants with ahk: the problem is solved if `Send` dot as `{U+002E}` or `{Text}.`. Any other variants cause the initial problem. 

I also test all possible in my layout symbols. It seems that the same problem is also with standard "-". All other symbols, including exotic ones, work fine.
Perhaps these two symbols are somehow particularly accepting?

**Comment by jgehrig** [comment] 2021-08-17 15:41
Marking as closed, since AHK is causing these issues.

If you'd really like to understand what is going on here, you'd need to trigger a `Debug` build.

You can un-comment these two lines in `src/gui/shell.cpp`:
```
// Uncomment for key input debugging and unit test writing.
// qDebug() << "QKeyEvent ev:" << ev;
// qDebug() << "  " << inp;
```

You can then inspect the logs for a `QKeyEvent` and the corresponding input string we send to Neovim.
https://github.com/equalsraf/neovim-qt/wiki#i-cant-see-debug-messages-in-windows

**Closed by jgehrig** 2021-08-17 15:41 UTC
