### ISSUE TITLE
Strange mouse pointer behavior at background jobs

### ISSUE THREAD

**Issue by przepompownia** [equalsraf/neovim-qt#919] opened 2021-08-14 10:31 UTC
Please see at the video:

https://user-images.githubusercontent.com/11404453/129443043-4ac83a81-f5ce-4f84-abe5-39ba088a1c72.mp4

It happens with GNOME Shell, Wayland. The command used to demonstrate comes from vim-fugitive. What other information can be useful to debug this behavior? 

As I remember some time ago `!ping 8.8.8.8` was another test command to show it but currently the pointer behaves as expected (continuously rotating circle in my env.).

**Comment by jgehrig** [comment] 2021-08-16 02:12
@przepompownia 

It looks like this is related to the cursor busy state. Usually, I use `:terminal` to enter the busy state. I think `!ping` enters the same mode.

> What other information can be useful to debug this behavior?

Do you have the ability to easy generate a debug build? `cmake -DCMAKE_BUILD_TYPE=Debug ..`

The following modifications to `shell.cpp` may help debug the scenario:
```
 void Shell::handleBusy(bool busy)
 {
+	qDebug() << "handleBusy!" << busy;
```

```
 void Shell::setCursorFromBusyState() noexcept
 {
 ...
 
 	if (cursor().shape() != desiredCursor) {
 		setCursor(desiredCursor);
+		qDebug() << "setCursor:" <<desiredCursor;
 	}
 }
```
```
 void Shell::mouseMoveEvent(QMouseEvent *ev)
 {
+	qDebug() << "mouseMoveEvent";
 	setCursorFromBusyState();
```

> It happens with GNOME Shell, Wayland.

Have you been able to reproduce the issue in other configurations?

Or is this just a description of the environment you're currently using?

**Comment by przepompownia** [comment] 2021-08-16 08:06
@jgehrig thank you for the debug hints.
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Neovim API version compatible with 0 supported 8
ginit.vim error  QVariant(QVariantList, (QVariant(qulonglong, 0), QVariant(QByteArray, "Vim(call):E117: Unknown function: GuiWindowFullScreen")))
mouseMoveEvent
handleBusy! true
setCursor: Qt::WaitCursor
handleBusy! false
setCursor: Qt::ArrowCursor
handleBusy! true
setCursor: Qt::WaitCursor
handleBusy! false
setCursor: Qt::ArrowCursor
handleBusy! true
setCursor: Qt::WaitCursor
handleBusy! false
setCursor: Qt::ArrowCursor
handleBusy! true
setCursor: Qt::WaitCursor
handleBusy! false
setCursor: Qt::ArrowCursor
handleBusy! true
setCursor: Qt::WaitCursor
handleBusy! false
setCursor: Qt::ArrowCursor
handleBusy! true
setCursor: Qt::WaitCursor
handleBusy! false
setCursor: Qt::ArrowCursor
handleBusy! true
setCursor: Qt::WaitCursor
handleBusy! false
setCursor: Qt::ArrowCursor
handleBusy! true
setCursor: Qt::WaitCursor
handleBusy! false
setCursor: Qt::ArrowCursor
handleBusy! true
setCursor: Qt::WaitCursor
handleBusy! false
setCursor: Qt::ArrowCursor
handleBusy! true
setCursor: Qt::WaitCursor
handleBusy! false
setCursor: Qt::ArrowCursor
handleBusy! true
setCursor: Qt::WaitCursor
handleBusy! false
setCursor: Qt::ArrowCursor
handleBusy! true
setCursor: Qt::WaitCursor
handleBusy! false
setCursor: Qt::ArrowCursor
handleBusy! true
setCursor: Qt::WaitCursor
handleBusy! false
setCursor: Qt::ArrowCursor
...
```
The whole log takes about 15k lines but there is nothing new below the above head. Is it enough information?

**Comment by jgehrig** [comment] 2021-08-17 02:11
Yes, that info is helpful!

It indicates something is causing Neovim to go into and out of busy mode rapidly. The only way to trigger busy mode is via an event from Neovim. This suggests the bug *may* be outside of `neovim-qt` code.

Can you reproduce this with minimal configuration?

For example:
`nvim-qt -- -u init.vim`

init.vim:
```
/* minimum number of options to trigger issue*/
``` 

A complete (minimal) set of steps would be helpful, so I can inspect the issue on my machine.

**Comment by przepompownia** [comment] 2021-08-18 07:45
It's possible that switching comes from fugitive.

To make the debugging easier: by what ways can I trigger busy mode?

After increasing verbosity to 12 I noticed repeatable calls:
```
calling function fugitive#Resume[4]..<SNR>141_RunWait[5]..<SNR>141_RunTick

function fugitive#Resume[4]..<SNR>141_RunWait[5]..<SNR>141_RunTick returning #1

continuing in function fugitive#Resume[4]..<SNR>141_RunWait

calling function fugitive#Resume[4]..<SNR>141_RunWait[6]..<SNR>141_RunEcho

function fugitive#Resume[4]..<SNR>141_RunWait[6]..<SNR>141_RunEcho returning #0

continuing in function fugitive#Resume[4]..<SNR>141_RunWait
```


https://github.com/tpope/vim-fugitive/blob/master/autoload/fugitive.vim

**Comment by jgehrig** [comment] 2021-08-18 15:06
> To make the debugging easier: by what ways can I trigger busy mode?

The easiest way to enter busy mode is with `:terminal`. Your `!ping 8.8.8.8` works well too.

**Comment by jgehrig** [comment] 2021-09-21 04:49
Marking this as closed based on the information above.

It looks like fugitive is trigger rapid entry/exit from busy mode.

**Closed by jgehrig** 2021-09-21 04:49 UTC

**Comment by przepompownia** [comment] 2021-09-21 09:33
Yes, it's most probably fugitive's issue. In the meantime I observed that this switching takes place less frequently, but I needed some free time to verify it.
