### ISSUE TITLE
GuiFont doesn't work

### ISSUE THREAD

**Issue by FUQQZe11** [equalsraf/neovim-qt#829] opened 2021-03-21 20:28 UTC
I installed _Neovim-qt_ on _WSL Ubuntu 20.04 LTS_(_sudo apt install neovim-qt_), create _ginit.vim_ file and add _Guifont DejaVu Sans Mono:h13_ in it, but it isn't work. When i try _:GuiFont_ in _nvim_ it return error. I think maybe _GUI_ doesn't installed, but don't know how i can check it. When i write _nvim-qt --help_ it work.

**Comment by jgehrig** [comment] 2021-03-22 02:35
Give this a try:
https://github.com/jgehrig/neovim-qt/tree/jg-readme#why-are-the-gui-commands-missing

This scenario is a common user frustration, and I am trying to improve the README... This would be a good test of the new instructions!

If you still have trouble after reading that snippet, please let me know. I'll help you fix the problem and update the FAQ.

Pull Request #821

**Comment by jgehrig** [comment] 2021-03-22 02:36
Closing, since this is a configuration issue. Feel free to keep posting here.

**Closed by jgehrig** 2021-03-22 02:36 UTC

**Comment by FUQQZe11** [comment] 2021-03-22 11:19
It still don't work, when I use "_:GuiFont DejaVu Sans Mono:h20_"(for example) nothing happens("_:GuiFont_" always print "_No GuiFont is set_"). When I try "_nvim-qt_" in my WSL it print: 
```
 qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb. 
```
and "_nvim-qt --version_":
```
Unknown option 'version'.
```
My "_ginit.vim_":
```
Enable Mouse
set mouse=a

" Set Editor Font
if exists(':GuiFont')
      " Use GuiFont! to ignore font errors
        GuiFont {font_name}:h{size}
endif

" Disable GUI Tabline
if exists(':GuiTabline')
        GuiTabline 0
endif

" Disable GUI Popupmenu
if exists(':GuiPopupmenu')
        GuiPopupmenu 0
endif

" Enable GUI ScrollBar
if exists(':GuiScrollBar')
        GuiScrollBar 1
endif

" Right Click Context Menu (Copy-Cut-Paste)
nnoremap <silent><RightMouse> :call
GuiShowContextMenu()<CR>
inoremap <silent><RightMouse> <Esc>:call
GuiShowContextMenu()<CR>
vnoremap <silent><RightMouse> :call
GuiShowContextMenu()<CR>gv
```
"_init.vim_":
```
set encoding=UTF-8

call plug#begin('~/.vim/plugged')
Plug 'scrooloose/nerdtree'
Plug 'OmniSharp/omnisharp-vim'
Plug 'vim-airline/vim-airline'
"Plug 'ervandew/supertab'
Plug 'ryanoasis/vim-devicons'
"Plug 'SirVer/ultisnips'
Plug 'equalsraf/neovim-gui-shim'
call plug#end()

"COLORSCHEME
syntax on
"colorscheme OceanicNext
set guifont=DejaVu\ Sans\ Mono:h18
set keymap=russian-jcukenmac
""Язык ввода при старте Вима - Английский
set iminsert=0
"Аналогично настраивается режим поиска
set imsearch=0
```

**Comment by jgehrig** [comment] 2021-03-22 17:50
There are a few issues going on here.

**First**
The `GuiFont` issue is caused by a missing "shim" layer. These commands are provided by a vim plugin.

You may be able to bypass the need for`GuiFont` with `:set guifont={your_font_here}` instead, called directly from `init.vim`

If you need `:GuiFont!`, you can install the plugin with one of two options:
1. Set the environment variable `NVIM_QT_RUNTIME_PATH`.
2. Use the plugin: `Plugin 'equalsraf/neovim-gui-shim`

Usually neovim-qt is able to automatically load the shim plugin. On non-standard installs, the path should be explicitly specified.

On WSL + nvim + neovim-qt, most users run an instance of `nvim` and connect to it from `neovim-qt` running on native Windows natively. Use `Plugin 'equalsraf/neovim-gui-shim` and call `GuiFont` after the plugin loads in `init.vim`.

**Second**
The `nvim-qt --version` command is only supported in recent releases. This suggests you are not running the latest version.

Running the latest version of neovim-qt is helpful because it provides diagnostic info:
```
NVIM-QT v0.2.17.9999
Build type: Release
Compilation:-march=native -O2 -pipe -Wall -Wextra -Wno-unused-parameter -Wunused-variable -std=c++11
Qt Version: 5.15.2
Environment: 
  nvim: nvim
  args: --cmd let &rtp.=',/usr/bin/../share/nvim-qt/runtime' --cmd set termguicolors
  runtime: /usr/bin/../share/nvim-qt/runtime

...
```

**Third**
The `qt.qpa.xcb: could not connect to display` error suggests neovim-qt cannot connect to X11/Wayland from WSL.

You are probably running WSL headless. You need to start an instance of `nvim`, and connect to it with neovim-qt. 

Here are some useful links:
https://github.com/equalsraf/neovim-qt/wiki#how-do-i-connect-to-a-running-neovim-instance
https://github.com/mhinz/neovim-remote

**Comment by jgehrig** [comment] 2021-03-22 17:53
If you can...

Please, let me know what information wasn't clear in the [README link](https://github.com/jgehrig/neovim-qt/tree/jg-readme#why-are-the-gui-commands-missing) from above and I will try to improve it.

**Comment by FUQQZe11** [comment] 2021-03-22 19:14
Thank you so much, will try install _neovim-qt_ on Windows with _neovim_ on WSL. "_You may be able to bypass the need forGuiFont with :set guifont={your_font_here} instead, called directly from init.vim_" - that only problem is because i try install _neovim-qt_, _:set guifont_ don't work for me, i think because _neovim_ haven't GUI.

**Comment by jgehrig** [comment] 2021-03-22 20:17
No problem! :smiley: 

I'd recommend using the latest release of neovim-qt: `0.2.16.1`. On Windows, it is included with Neovim `0.5.0`.

Using the latest release helps rule out "When was that feature added?" issues. The option `:set guifont` has not always been available...

Here is a quick demo:
![Peek 2021-03-22 16-12](https://user-images.githubusercontent.com/11207308/112052430-81a61f80-8b29-11eb-968a-0254e17eca94.gif)

It doesn't work for all cases, such as when your font requires a `GuiFont!`. The bang allows fonts Qt marked as non-monospace.

**Comment by FUQQZe11** [comment] 2021-03-23 15:55
Can i ask you, how can i install neovim-qt on windows, i need install neovim and clone git https://github.com/equalsraf/neovim-qt and build it like in guide, and then connect with WSL?

**Comment by jgehrig** [comment] 2021-03-23 21:36
See:
https://github.com/jgehrig/neovim-qt/tree/jg-readme#windows

**Comment by hinell** [comment] 2022-11-17 21:30
@jgehrig I think you have to update Wiki pages on this.
