### ISSUE TITLE
Attach to already running instance of neovim-qt

### ISSUE THREAD

**Issue by qazip** [equalsraf/neovim-qt#847] opened 2021-05-07 09:37 UTC
If I have a file opened on neovim-qt and open a new one (by using the terminal, i.e., "neovim-qt another_file.py"), I would like for this new file to be opened in the already running instance of neovim-qt. Right now, it opens a new window/instance of nvim-qt.

**Comment by equalsraf** [comment] 2021-05-07 11:45
nvr is your best bet to control neovim - see https://github.com/mhinz/neovim-remote - it should cover this and similar cases.

It works with with neovim in general (not just neovim-qt)

**Comment by qazip** [comment] 2021-05-07 13:06
I did not know about that project. Thank you!

> It works with with neovim in general (not just neovim-qt)

So, it works with neovim-qt, right? Do you know how to force an editor in the nvr? I had a look at the README and --help page but couldn't find. I can make it work with the regular nvim, just not the gui...

**Comment by equalsraf** [comment] 2021-05-07 13:46
> So, it works with neovim-qt, right?

Yes, neovim-qt just runs nvim in the background so everything should be similar.

For example in my linux system, I can start nvim-qt like this

```
$ NVIM_LISTEN_ADDRESS=/tmp/testing-nvr nvim-qt
```

nvr can also list running instances (the second in this list is the nvim-qt i just started)

```
$ nvr --serverlist
/tmp/nvime9yl10/0
/tmp/testing-nvr
```

and i can open a new tab using

```
$ nvr --servername /tmp/testing-nvr --remote-tab /tmp/test.md
```

The one thing that might not be straightforward is to start a new editor. nvr supports the `$NVR_CMD` environment variable to start a custom instance of nvim.

https://github.com/mhinz/neovim-remote/blob/1ec7c6c76a66d8d381f54570d6fdd3079c190ba5/nvr/nvr.py#L77

However I dont think you can simply set NVR_CMD as `nvim-qt` (or `nvim-qt --no-fork`). When i  tried the editor started but i got this error

```
[!] Unable to attach to the new nvim process. Is `nvim-qt --nofork` working?
```

I would need to look closer at this

https://github.com/mhinz/neovim-remote/blob/1ec7c6c76a66d8d381f54570d6fdd3079c190ba5/nvr/nvr.py#L58

Note: this tries to attach 10 times, with a sleep time of 0.2 - maybe the issue is that it takes "too long" for nvim to start and the attach fails. It might be worth investigating raising that sleep time.

**Comment by qazip** [comment] 2021-05-08 07:25
I am trying to create a simple bash function to have neovim-qt behave like sublime. That is, attach to the same window when neovim-qt is already running, or open a new window when it is not. Something like this:
```

n(){
    local running_servers=$(nvr --serverlist)
    local n_server_name=/tmp/nvr_nvim-qt
    if [[ -z "$running_servers" || -z $1 ]]; then
        echo "here0"
        NVIM_LISTEN_ADDRESS=$n_server_name nvim-qt
    elif [[ $running_servers == *"$n_server_name"* ]]; then
        echo "here1"
        local running_client=$(procs nvim-qt)
        if [[ $running_client == *"nvim-qt"* ]]; then
            echo "here2"
            nvr --servername $n_server_name --remote-tab $1
        else
            echo "here3"
            rm $n_server_name
            NVIM_LISTEN_ADDRESS=$n_server_name nvim-qt $1
        fi
    fi
}
```

There is probably a better/easier way to do it, but meh. However, it seems like removing the /tmp/ files/folder does not clear anything as nvr --serverlist still returns the same addresses. Any idea on how to tackle this?

**Comment by equalsraf** [comment] 2021-05-08 20:39
I did some tests with nvr here:

1. Increasing the timeout value does help (e.g. from 0.2 to 0.4 systematically works for me) the nvr call becomes `NVR_CMD=nvim-qt nvr`
2. I did observe some issues e.g. if the socket was left behind in a previous execution then attachment still fails

For the script you were writing. It looks like what you are presetting you NVIM_LISTEN_ADDRESS variable, and use serverlist to determine if the server is up. You can get the same effect by calling nvr to test the connection for you, e.g. 

```
$ nvr -s --nostart --servername /tmp/nvr_nvim-qt  --remote-expr "'OK'"     
OK
```
the exit status is `0`

```
$ nvr -s --nostart --servername /tmp/nosuchserver  --remote-expr "'OK'"
```

this prints nothing, but exit status is `1`

This should avoid issues with leftover sockets, treating those as errors and allowing you to remove them.

**Comment by equalsraf** [comment] 2021-05-09 14:18
> If I open nvim-qt (with the script using --servername /tmp/nvr_nvim-qt) and close it with my window manager's kill command

I would expect this to kill everything (close nvim-qt, close the associated nvim, and remove the socket /tmp/nvr_nvim-qt)

> It doesn't return exit status 1 nor 0, it just hangs, waiting for something. Is this nvim-qt related or nvr related?

I would suspect it is either nvr or neovim.

A couple of things to check

- is the socket still there? in /tmp/nvr_nvim-qt
- is nvim still running in the background?
- does this stop happening after a while?

**Comment by jgehrig** [comment] 2021-05-25 02:20
Marking as closed: `nvr` is the tool for this use-case.

Feel free to keep commenting with additional questions (or once you get a working example).

**Closed by jgehrig** 2021-05-25 02:20 UTC
