### ISSUE TITLE
No more guicursor in insert mode in terminal

### ISSUE THREAD

**Issue by lgeo3** [equalsraf/neovim-qt#635] opened 2020-01-31 09:02 UTC
Since the last few commits I don't see the gui cursor in insert mode anymore (macos). Do you know what I can check ?

**Comment by jgehrig** [comment] 2020-01-31 12:54
Can you provide more details?
- platform
- version
- install type
- when this happens, or a rough breaking commit 

I can't think of anything that would cause this off the top of my head...

**Comment by lgeo3** [comment] 2020-01-31 13:51
platform: macos
version: neovim version NVIM v0.4.0-1773-g0e8ee37ef
install type: from source/git
breaking commit: commit 70f402b4029beaa15e32a4a0cc7d8b396b84ef74 

Without this last commit it works fine.

**Comment by jgehrig** [comment] 2020-02-03 04:33
I cannot reproduce. Can you elaborate on what is going wrong?

![image](https://user-images.githubusercontent.com/11207308/73625622-a4b6fc80-4613-11ea-8072-70713aa493b6.png)

Is the cursor still gone with an empty configuration?
`nvim-qt -- -u NONE`

**Comment by jgehrig** [comment] 2020-07-20 04:38
Closing this issue.

Feel free to re-open along with more details if this is still broken.

**Closed by jgehrig** 2020-07-20 04:38 UTC
