### ISSUE TITLE
nvim process crash when I do nvr

### ISSUE THREAD

**Issue by eyalk5** [equalsraf/neovim-qt#656] opened 2020-03-14 15:14 UTC
Hi,
It happens when  I do a backward search from skim. Neovim's process  crashes when I run the following script:

/Users/eyalkarni/.pyenv/shims/nvr --nostart --servername \`cat /tmp/curserver\`  --remote-send "$1GzOzz"

where $1 contains the line. 

Now, it doesn't happen when I tried to run it in a loop. Just when I double click the mouse to trigger it and just sometimes. So, I wasn't able to reproduce it in a comfortable way. But it happens a lot. 

Any idea - or suggestion on how to debug.

Thanks.

**Comment by jgehrig** [comment] 2020-03-15 02:47
@eyalk5

It helps to have clear reproducible steps when filing bugs like this... I cannot follow what you're doing.

You should provide a set of steps that anyone can easily follow. Provide a minimal example, and assume you are starting from a fresh install. All scripts, configurations, and options should be provided or attached.

A few thoughts:
1. What makes you think this is a `neovim-qt` issue? The `nvim` process is crashing...
2. Try performing the same action with `nvim` and `nvim-qt`. Is there a behavior difference?
3. Attach a debugger to `nvim`. What is the call stack on crash?
4. Attach a debugger to `nvim-qt`. What is the process doing?

**Comment by jgehrig** [comment] 2020-08-06 04:50
Cannot reproduce. Please comment if this is still an issue in the latest release.

Marking as closed.

**Closed by jgehrig** 2020-08-06 04:50 UTC
