### ISSUE TITLE
Searching with '/' causes mouse pointer to appear and flicker

### ISSUE THREAD

**Issue by markonm** [equalsraf/neovim-qt#244] opened 2017-02-17 01:43 UTC
OS: Windows.  Neovim: 0.2

**Comment by equalsraf** [comment] 2017-02-17 09:54
Confirmed in Linux too.

Interestingly it happens not when we press '/' but when pressing the first input after '/'.

This seems to be related to the `busy_start` and `busy_stop` events. Whenever pressing a key in search mode, a pair of events are received by the GUI. The busy start event changes the pointer to a waiting cursor, and the busy_stop to the default cursor. Since this happens too fast we just see the cursor showing up.

I guess we need to check the current cursor state when handling a busy_start.

**Comment by jgehrig** [comment] 2020-09-06 03:36
I don't see this issue anymore.

Perhaps an upstream change was made. I no longer see `busy_start` or `busy_stop` events for `/` search in`NVIM v0.4.3`.

The client-side issue has also likely been addressed too in #655 or #730.

Marking as closed.

**Closed by jgehrig** 2020-09-06 03:36 UTC
