### ISSUE TITLE
shift+space prints ;2u in terminal

### ISSUE THREAD

**Issue by fuelen** [equalsraf/neovim-qt#728] opened 2020-07-29 11:23 UTC
```
$ nvim-qt --version
NVIM-QT v0.2.16.1
Build type: Release
Compilation:-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors
Qt Version: 5.15.0
Environment: 
  nvim: nvim
  args: --cmd let &rtp.=',/usr/share/nvim-qt/runtime' --cmd set termguicolors
  runtime: /usr/share/nvim-qt/runtime

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Скомпілював  builduser

Характеристики: +acl +iconv +tui
See ":help feature-compile"

   системний vimrc: "$VIM/sysinit.vim"
  заміна для $VIM: "/usr/share/nvim"

Run :checkhealth for more info

```
steps to reproduce:
open neovim-qt
run :terminal
go to insert mode
press Shift+Space

It is annoying, because while writing `iex -S mix` I always get `iex -S;2umix` and I do not experience this in other terminal emulators :)

**Comment by jgehrig** [comment] 2020-07-29 14:30
Sorry for the troubles!

I cannot reproduce, but I would guess there is an environment difference.

A few questions:

1. What platform are you using? Windows, Linux, or MacOS?
2. Does the issue still reproduce without your `vimrc`, use `nvim-qt -- -u NONE`
3. Are you using an non-english keyboard layout/localization?
4. Did this start with `v0.2.16`?
5. Can you easily build `neovim-qt` from source?

There have been changes to the input layer recently, and I am aware of some international keyboard layout issues #720. This is likely semi-related. I can address it at the same time.

The easiest way to fix this is to provide `qDebug` `QKeyEvent` output as per #683. Unfortunately, this will require you to build `neovim-qt`. Alternatively, I will need more detailed information to provide it myself. ( I really need to add that argument... )

Once there is `QKeyEvent` info, I can write tests and fix the issue.

**Comment by fuelen** [comment] 2020-07-29 15:31
1. Arch Linux
2. yes, I can reproduce with nvim-qt -- -u NONE
3. I use several keyboard layouts, but this happens on english layout. My $LANG is uk_UA.UTF-8
4. I don't know
5. yes, will try package from AUR

**Comment by fuelen** [comment] 2020-07-29 15:39
issue reproduces on fresh package neovim-qt-git v0.2.16.r15.gcc9adcd-1

**Comment by jgehrig** [comment] 2020-07-29 16:53
Thanks for the info. All good, we're headed in the right direction.

**Comment by jgehrig** [comment] 2020-07-29 16:58
> issue reproduces on fresh package neovim-qt-git v0.2.16.r15.gcc9adcd-1

I'm also on git `master`, but cannot reproduce. My `echo $LANG` is `en_US.utf8` on Gentoo/Linux.

There is a variable/settings difference between our systems somewhere...

> Can you easily build neovim-qt from source?

I should have been more clear. It would greatly help me if you can run a patched build. Sorry this is so inconvenient, I really need to finish #683...

Is the AUR is capable of applying patches to source-based packages? I'm only familiar with how to do this on Gentoo/Portage... If needed, I can walk you through setting up a manual build from source.

We need to do the same as: https://github.com/equalsraf/neovim-qt/issues/720#issuecomment-653919163

We need to un-comment the lines in `Shell::keyPressEvent(...)` in file `src/gui/shell.cpp`:
```C++
	// Uncomment for key input debugging and unit test writing.
	// qDebug() << "QKeyEvent ev:" << ev;
	// qDebug() << "  " << inp;
```

**Comment by fuelen** [comment] 2020-07-29 20:53
here is what I've got:
```
$ cat $NVIM_QT_LOG 
Neovim API version compatible with 0 supported 6
Received unknown option "pumblend" QVariant(qulonglong, 0)
Received unknown option "ext_multigrid" QVariant(bool, false)
Received unknown option "ext_hlstate" QVariant(bool, false)
Received unknown option "ext_termcolors" QVariant(bool, false)
Received unknown option "ext_messages" QVariant(bool, false)
Received unknown redraw notification "update_menu" ()
Received unknown redraw notification "update_menu" ()
Received unknown redraw notification "update_menu" ()
Received unknown option "ext_messages" QVariant(bool, false)
Received unknown option "ext_messages" QVariant(bool, false)
Received unknown option "ext_messages" QVariant(bool, false)
Received unknown option "ext_messages" QVariant(bool, false)
Received unknown option "ext_messages" QVariant(bool, false)
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Colon, ShiftModifier, text=":")
   ":"
QKeyEvent ev: QKeyEvent(KeyPress, Key_T, text="t")
   "t"
QKeyEvent ev: QKeyEvent(KeyPress, Key_E, text="e")
   "e"
QKeyEvent ev: QKeyEvent(KeyPress, Key_R, text="r")
   "r"
QKeyEvent ev: QKeyEvent(KeyPress, Key_M, text="m")
   "m"
QKeyEvent ev: QKeyEvent(KeyPress, Key_I, text="i")
   "i"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Tab, text="\t")
   "<Tab>"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Return, text="\r")
   "<Enter>"
QKeyEvent ev: QKeyEvent(KeyPress, Key_A, text="a")
   "a"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Space, ShiftModifier, text=" ")
   "<S-Space>"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Control, ControlModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Backslash, ControlModifier, text="\u001C")
   "<C-Bslash>"
QKeyEvent ev: QKeyEvent(KeyPress, Key_N, ControlModifier, text="\u000E")
   "\u000E"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Colon, ShiftModifier, text=":")
   ":"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Q, text="q")
   "q"
QKeyEvent ev: QKeyEvent(KeyPress, Key_Return, text="\r")
   "<Enter>"
Neovim requested a GUI close
```

**Comment by jgehrig** [comment] 2020-07-29 21:20
Okay, I see what is going on. I completely missed that you were in `:terminal` mode. Doh!

The space key event is definitely malformed:
```
QKeyEvent ev: QKeyEvent(KeyPress, Key_Shift, ShiftModifier)
   ""
QKeyEvent ev: QKeyEvent(KeyPress, Key_Space, ShiftModifier, text=" ")
   "<S-Space>"
```

Key_Space should be sent without the shift `<S-` modifier. The fix should be easy. I will push something out shortly.

**Comment by jgehrig** [comment] 2020-07-29 21:20
Thank you for the thorough bug report and assistance!

Greatly appreciated.

**Comment by jgehrig** [comment] 2020-07-31 04:52
This issue is a duplicate of #437.

**Comment by jgehrig** [comment] 2020-07-31 14:34
This issue is a duplicate of #259.

**Closed** 2020-08-04 15:15 UTC
