### ISSUE TITLE
Background color after the line changes on repaint (fixed at subsequent repaints)

### ISSUE THREAD

**Issue by eudoxos** [equalsraf/neovim-qt#620] opened 2019-12-29 09:10 UTC
When I hit Ctrl-L for repaint, the background switches to a different (lighter, like statusline?) color; subsequent repaint fixes the background color.

![vokoscreen-2019-12-29_10-06-27](https://user-images.githubusercontent.com/1029876/71554688-f1128980-2a22-11ea-880c-14482dc7fa58.gif)

I am using locally compiled a5e126e with SpaceVim, colorscheme gruvbox dark. If you need any more information, I am ready to get those.

Version information here:

```
NVIM-QT v0.2.14.0
Build type: Release
Compilation: -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors
Environment: 
  nvim: nvim

NVIM v0.5.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-ZYxjFg/neovim-0.5.0+ubuntu1+git201912260029-5f1aec5-00e710e=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-ZYxjFg/neovim-0.5.0+ubuntu1+git201912260029-5f1aec5-00e710e/build/config -I/build/neovim-ZYxjFg/neovim-0.5.0+ubuntu1+git201912260029-5f1aec5-00e710e/src -I/build/neovim-ZYxjFg/neovim-0.5.0+ubuntu1+git201912260029-5f1aec5-00e710e/.deps/usr/include -I/usr/include -I/build/neovim-ZYxjFg/neovim-0.5.0+ubuntu1+git201912260029-5f1aec5-00e710e/build/src/nvim/auto -I/build/neovim-ZYxjFg/neovim-0.5.0+ubuntu1+git201912260029-5f1aec5-00e710e/build/include
Compiled by buildd@lgw01-amd64-043

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by jgehrig** [comment] 2019-12-30 06:08
@eudoxos

I cannot reproduce the issue. Could there be an issue with your specific configuration and nvim-qt?

A few things to try:
1. Does this issue appear in terminal Neovim?
2. Can you reproduce this issue with a minimal configuration? `nvim-qt -- -u minimal.vim`
3.  What is the output of `:hi CursorLine`?
4. Can you reproduce this issue without SpaceVim?

Some further debugging will be required to find a root cause :)

**Comment by jgehrig** [comment] 2020-08-06 04:49
Cannot reproduce. Please comment if this is still an issue with the latest release.

Marking as closed.

**Closed by jgehrig** 2020-08-06 04:49 UTC
