### ISSUE TITLE
Opening the same file twice stalls neovim-qt

### ISSUE THREAD

**Issue by RedX2501** [equalsraf/neovim-qt#301] opened 2017-06-23 13:08 UTC
I have added a `Open with NeoVIM` to my context menu with the following command line:

    "D:\Utilities\neovim\bin\nvim-qt.exe" "%1"

If I open the same file twice through the context menu the second instance will not open. It will complain that neovim is not responding. 

Closing the first window (which was working fine) and clicking retry on the second window will open the file.

**Comment by equalsraf** [comment] 2017-06-23 13:57
What happens if you open it from the terminal?

I suspect this is a duplicate of https://github.com/equalsraf/neovim-qt/issues/78

**Comment by RedX2501** [comment] 2017-06-23 14:03
Same result with

```
start nvim-qt.exe a_file.txt
start nvim-qt.exe a_file.txt
```

and with

```
nvim-qt.exe a_file.txt
nvim-qt.exe a_file.txt
```

**Comment by equalsraf** [comment] 2017-06-23 14:07
> What happens if you open it from the terminal?

Ups my mistake, I was not clear. What happens if you open with `nvim` from the terminal?

**Comment by RedX2501** [comment] 2017-06-23 14:08
Just did that. See previous comment.

**Comment by equalsraf** [comment] 2017-06-23 14:26
**nvim** no **nvim-qt**, I suspect its complaining.with an error message about the swap file or something.

**Comment by RedX2501** [comment] 2017-06-23 14:44
First console (`cmd`)
```
nvim.exe log.txt
```
Second console (`cmd`)
```
nvim.exe log.txt
```
Works fine:
![grafik](https://user-images.githubusercontent.com/929932/27487147-27c1e04e-5833-11e7-9791-d9d749f5285e.png)

**Closed** 2017-08-15 13:08 UTC
