### ISSUE TITLE
neovim-qt exits without warning when there is a lot of output in a terminal buffer.

### ISSUE THREAD

**Issue by sras** [equalsraf/neovim-qt#457] opened 2018-09-04 01:00 UTC
When I start a program that keeps on writing output to terminal buffer, neovim-qt exits after a while. I think this was working fine, and the issue started only recently. I have updating to the latest version of neovim-qt and the nvim version is 0.2.3-1. My operating system is Ubuntu 16.06

This issue does not seem to be present in neovim.

**Comment by sras** [comment] 2018-09-04 16:27
Not sure if this is relevant, but It seems that the issue happen when the program that is running in the terminal has output nearly 16MB of content into the terminal.

**Comment by equalsraf** [comment] 2018-09-04 20:31
hi @sras.

What are you using to reproduce this? Does a cat of a 16M file in a terminal buffer cause this?

**Comment by sras** [comment] 2018-09-05 01:31
I was using this command `tree 2>&1 | tee /tmp/tree.txt` to generate output and save it to a file at the same time. But I doubt it is the size of the content. Because when I do the same now, the output file is at 70Mb when the issue happens. Also, when I use a bash loop to print the same line of text endlessly, the issue never happens.

**Comment by sras** [comment] 2018-09-05 02:02
@equalsraf 

Here are a couple more data points

1. When I cat the text file that was produced by the 'tree' command in the neovim-qt terminal buffer, it does not crash. But this output dump only have content that was generated until the crash.

2. When I cat the text file that was produced by the `tree` command in a standalone terminal, and thus have the full output in it; so when I cat this file from a nvim-qt terminal buffer, the crash happens.

3. When I repeat step 2, the crash happens, but at a different point in the file.

So right now it seems that the crash is triggered by some byte sequence in the output, but only sometimes..

**Comment by sras** [comment] 2018-09-05 04:30
@equalsraf 

Also tried filtering characters from the output

These does not cause the issue

cat /tmp/tree.txt | tr -d [:print:] 
cat /tmp/tree.txt | tr -d [:graph:] 

These does

cat /tmp/tree.txt | tr -d [:cntrl:] 
cat /tmp/tree.txt | tr -d [:punct:] 
cat /tmp/tree.txt | tr -d [:space:]

**Comment by equalsraf** [comment] 2018-09-05 17:58
Yayks. I tried a similar approach here but even after 100Mb of data I cannot reproduce.

Any chance you can try to get a trace of the crash with gdb?

**Comment by sras** [comment] 2018-09-06 02:06
@equalsraf 

When I add a printf here

```
/** The Neovim process has exited */
void Shell::neovimExited(int status)
{
	setAttached(false);
	if (status == 0 && m_nvim->errorCause() == NeovimConnector::NoError) {
                printf("Close message");    // <----
		close();
	}
}
```

It gets executed when the issue happen. Does it mean everything is normal, and there was no crash? How is this possible?

**Comment by sras** [comment] 2018-09-06 03:42
@equalsraf 

Can you tell me if this is normal? What are those <defunct> nvim process that seems to be spawned by neovim-qt. Also is it normal to have two nvim embeded processes?

```
ps aux | grep nvim
sras      1445  0.0  0.0  14228   940 pts/21   S+   09:10   0:00 grep --color=auto nvim
sras      9587  0.4  0.7 188544 118444 pts/2   Tl   Sep05   5:51 nvim
sras      9591  0.0  0.0 248668  2316 ?        Ssl  Sep05   0:02 nvim
sras@~ : nvim-qt
sras@~ : ps aux | grep nvim
sras      1449 10.0  0.3 779332 51648 ?        Sl   09:10   0:00 /home/sras/.local/bin/nvim-qt --nofork
sras      1459  3.5  0.0  47156 12740 ?        S    09:10   0:00 nvim --embed --headless --cmd let &rtp.=',/home/sras/.local/share' --cmd set termguicolors
sras      1460  0.0  0.0      0     0 ?        Z    09:10   0:00 [nvim] <defunct>
sras      1465  3.0  0.0 248664  2668 ?        Ssl  09:10   0:00 nvim --embed --headless --cmd let &rtp.=',/home/sras/.local/share' --cmd set termguicolors
sras      1489  0.0  0.0  14228   980 pts/21   S+   09:10   0:00 grep --color=auto nvim
sras      9587  0.4  0.7 188544 118444 pts/2   Tl   Sep05   5:51 nvim
sras      9591  0.0  0.0 248668  2316 ?        Ssl  Sep05   0:02 nvim
```

**Comment by equalsraf** [comment] 2018-09-06 09:11
Ok for gdb we want to prevent nvim-qt from forking into a new process at startup by passing `--nofork`, something like this should do it

```sh
$ gdb nvim-qt
(...)
(gdb) r --nofork
Starting program: /usr/bin/nvim-qt --nofork
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffeb690700 (LWP 24118)]
[New Thread 0x7fffe3fff700 (LWP 24120)]
[New Thread 0x7fffe121f700 (LWP 24123)]
[New Thread 0x7fffd3fff700 (LWP 24124)]
[New Thread 0x7fffd37fe700 (LWP 24125)]
[New Thread 0x7fffd2ffd700 (LWP 24126)]
[New Thread 0x7fffd27fc700 (LWP 24127)]
[New Thread 0x7fffd1ffb700 (LWP 24128)]
[New Thread 0x7fffd17fa700 (LWP 24129)]
```

After this nvim-qt should be running and the gdb console should be blocked until it exits (or crashes).

> When I add a printf here

Yes that looks like a clean exit. That function should execute when the embeded nvim process exits.
However this depends on how you exited (`:q` or closing the window behave slightly differently).

> Also, the issue does not happen from a nvim's terminal buffer.

Hard to tell without further info. Maybe you just happen to trigger the bug through the terminal, but it could be unrelated to it.

> Can you tell me if the processes created by neovim-qt is as expected?

Seems ok except that you have two nvim processes.

> What are those nvim process that seems to be spawned by neovim-qt.

nvim-qt launches a headless nvim process and communicates with it via an rpc channel. So there is always one nvim process for every nvim-qt process.

> Also is it normal to have two nvim embeded processes?

No. Maybe it is still running from a previous nvim-qt crash?

Maybe the best way to clarify what process is crashing is to do this step by step. Try the following setup

1. In one terminal launch nvim with the command
`NVIM_LISTEN_ADDRESS=/tmp/test-nvimqt-crash nvim`
This will start nvim while listening in the socket /tmp/test-nvimqt-crash
2. In another terminal start nvim-qt as
`nvim-qt --nofork --server /tmp/test-nvimqt-crash`

You should now be able to test and see what happens in each process.

You can also run gdb on any of the two processes. To make your life easier the way to start an run a process in gdb in a single line is

```
gdb -ex run --args /usr/bin/nvim-qt --nofork
```

**Comment by sras** [comment] 2018-09-06 18:41
![image](https://user-images.githubusercontent.com/6322381/45173524-0a883480-b226-11e8-96c3-1f0cc8474f26.png)

This is the result of what you suggested. For the first couple of times, it didn't crash. But when I made nvim-qt to run fullscreen, the crash happened. When it happen, there is a message that was printed out into the terminal that is running nvim. As far as I can see, it says "Message is not an array".

Right now, it seems that I can get around crashing by explicitly connecting to an Nvim server started with headless flag.

**Comment by equalsraf** [comment] 2018-09-06 19:44
I'm confused about one thing in your output. Why are you calling nvim with --embed from your terminal? Did you want to use --headless? --embed will likely always cause an error because it expects the stdin/out to be used for rpc calls.

Based on the message from nvim-qt it seems nvim-qt exited cleanly "QLocalSocket: Remote closed" (so no crash). Either nvim exited or for some reason the local socket connection was closed.

Looking at the output in your terminal. It seems nvim-qt continued running, and nvim closed. The nvim message is a bit strange because of those weird symbols at the start - it seems that nvim is dumping some piece of memory into its output and that message string is in there.

As for the error message itself, it can be found in [neovim](https://github.com/neovim/neovim/blob/master/src/nvim/msgpack_rpc/helpers.c#L573) and its an api error message that is used when neovim receives an invalid rpc message. Which would suggest nvim-qt sent some kind of invalid rpc message. However if you were always using --embed instead of --headless then this would not be unexpected.

**Comment by sras** [comment] 2018-09-07 06:47
@equalsraf 

Ok. I think I have figured it out. Not all the way, though.

I think this was caused by a bug in nvim executable that I was using. My executable was from 0.2 branch. I was not using 0.3 version due to [this](https://github.com/neovim/neovim/issues/8723) issue.

So anyway, what I noticed is that when I run "nvim", just like that without any arguments or anything. It creates two nvim process and another zombie process. You can see this happen in the output of 'ps' I posted [earlier](https://github.com/equalsraf/neovim-qt/issues/457#issuecomment-418954709)

So, when I switched back to the latest neovim (nightly), I found this behavior has disappeared, ie running nvim does not create spurious processes, and with that also our bug also seems to be fixed.

Anyway, thanks for your time, and also for this beautiful front end for Neovim. I think it is the best out there. Cheers!

**Comment by equalsraf** [comment] 2018-09-07 10:09
Ok, closing this then.

Thanks @sras.

**Closed by equalsraf** 2018-09-07 10:09 UTC
