### ISSUE TITLE
'noshowmode' disables cursor change when insert mode is started

### ISSUE THREAD

**Issue by markonm** [equalsraf/neovim-qt#243] opened 2017-02-16 23:22 UTC
On Windows, when I use 'noshowmode' and start insert mode, cursor doesn't change it's shape from block to vertical line. Nevertheless, cursor shape is changed after subsequent typed letter.

**Comment by equalsraf** [comment] 2017-02-16 23:58
Interesting I see something too, but its a bit different. With noshowmode

1. I start insert mode and the block cursor turns into a line immediately
2. If I press escape the cursor remains a line until I trigger some other event.

With 'showmode' the cursor changes as soon as I leave insert mode.

**Comment by xtal8** [comment] 2017-02-17 00:27
I can reproduce what I reported only if I have `noshowmode` and `noshowcmd` options both enabled. I also reproduced your case. It shows only at the beginning of the line and only if something is already typed on the line.

**Comment by jgehrig** [comment] 2020-09-01 05:50
The cursor logic has changed to support `guicursor` since this bug was filed. I cannot reproduce.

Marking as closed. Please file a new bug if you still see issues.

**Closed by jgehrig** 2020-09-01 05:50 UTC
