### ISSUE TITLE
:help does not provide help

### ISSUE THREAD

**Issue by RedX2501** [equalsraf/neovim-qt#77] opened 2015-12-16 04:30 UTC
This is very likely not a neovim-qt issue but a neovim. Just starting here to be sure.
I just downloaded the latest neovim and neovim-qt from appveyor. 

When issuing :help command i get:

E433: No tags file
E149: sorry no help for help.txt

Not sure who should provide these.

Update: after looking around i found those files but it does not matter how i start neovim-qt it does not find the files. I guess i'd have to modify runtimepath for it to work? But it seems a bit to cumbersome for something that should be a package.

**Comment by equalsraf** [comment] 2015-12-16 09:28
This used to work but it regressed a while back and needs to be fixed upstream neovim/neovim#810. The problem is that the helpfiles need to be generated and installed when the packages are generated but recent changes have changed how this works.

**Comment by RedX2501** [comment] 2015-12-16 14:09
One solution it seems is to ```set VIMRUNTIME=<path to neovim>\share\nvim\runtime```. Found through https://github.com/neovim/neovim/issues/3852

**Comment by equalsraf** [comment] 2016-03-15 13:54
Closing, should be fixed in the windows PR upstream.

**Closed by equalsraf** 2016-03-15 13:54 UTC
