### ISSUE TITLE
Mouse wheel scrolling in splits

### ISSUE THREAD

**Issue by ethanxxxl** [equalsraf/neovim-qt#793] opened 2020-11-28 21:53 UTC
I have noticed two different issues with mouse wheel scrolling:

- mouse wheel scrolling does not work at all in the help split
- mouse wheel scrolling only scrolls the buffer that the cursor is in

In the terminal, and some other GUIs, when you move the scroll wheel, it scrolls whatever split that mouse pointer is currently hovering over. 

I am using Arch Linux with Gnome, and installed the program from the AUR. 

uname -a
`Linux desktop 5.9.10-arch1-1 #1 SMP PREEMPT Sun, 22 Nov 2020 14:16:59 +0000 x86_64 GNU/Linux`

nvim-qt --version
```
NVIM-QT v0.2.17.9999
Build type: Release
Compilation:-D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wextra -Wno-unused-parameter -Wunused-variable -std=c++11
Qt Version: 5.15.1
Environment: 
  nvim: nvim
  args: --cmd set termguicolors
  runtime: 

NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by jgehrig** [comment] 2020-11-28 23:05
Can you try these scenarios with #791?

There was a bug in the scroll event output. If that doesn't help, we can debug further.

Thanks for the bug report! 👍

**Comment by ethanxxxl** [comment] 2020-11-28 23:32
It seems that #791 fixes both of the issues that I was having.
Thanks!

**Comment by jgehrig** [comment] 2020-11-28 23:34
Sorry for the break. Glad to hear the issue is fixed with 791.

I'll try to merge the changes later this evening.

**Closed by jgehrig** 2020-11-28 23:34 UTC
