### ISSUE TITLE
Forward nvim arguments transparently

### ISSUE THREAD

**Issue by koppa** [equalsraf/neovim-qt#172] opened 2016-08-21 23:14 UTC
It would be nice to pass the all arguments to neovim directly without the `--` flag.
It should be no problem.
Currently only the `--embed` and `--help` flags are used by neovim and neovim-qt.

For example I often use the diff mode (-f).

**Comment by justinmk** [comment] 2016-08-22 01:14
See https://github.com/equalsraf/neovim-qt/issues/148

**Comment by equalsraf** [comment] 2016-08-22 07:09
#148 only addresses filenames. Flags such as `-f` still require using `--`.

**Comment by jgehrig** [comment] 2020-09-06 03:42
Related #449.

**Comment by equalsraf** [comment] 2022-02-06 16:27
Closing as a duplicate of https://github.com/equalsraf/neovim-qt/issues/449

**Closed by equalsraf** 2022-02-06 16:27 UTC
Labels: enhancement
