### ISSUE TITLE
Patched Nerd fonts do display properly

### ISSUE THREAD

**Issue by blayz3r** [equalsraf/neovim-qt#741] opened 2020-09-09 20:10 UTC
![image](https://user-images.githubusercontent.com/12205650/92648131-fb299f00-f2b6-11ea-95f4-1e196c2c2a0a.png)

Fira Mono NF

**Comment by jgehrig** [comment] 2020-09-09 20:59
Thanks for the bug report. However, I will need more details to help...

What isn't displayed properly?

Where did you get this font, and how did you install it?

Does this font display properly in other applications?

What version of `neovim-qt` are you using? See `nvim-qt --version`.

**Comment by blayz3r** [comment] 2020-09-09 21:04
The font look like they are breaking apart and I get this warning

![image](https://user-images.githubusercontent.com/12205650/92654872-7cd0fb00-f2be-11ea-9089-e28d118bf41f.png)

**Comment by jgehrig** [comment] 2020-09-09 21:22
> Warning: Font "InconsolataLGC NF" reports bad fixed pitch metrics

The first warning is by design and indicates your font contains characters of varying widths. It is not a true monospace font. 

It is usually safe to ignore. You can suppress this warning with `:GuiFont! <your font>`. See `:help GuiFont`.

>Where do I run the command:

Command prompt or PowerShell: `Win + R`, `cmd.exe`, `nvim-qt --version`

Based on your `nvim` version, I would guess you are running a recent release `0.2.15` or `0.2.16`.

> ![image](https://user-images.githubusercontent.com/11207308/92655705-d259d780-f2bf-11ea-873d-5fdff1b11ed4.png)

Does this picture also capture the display issue? Is the rendering issue before and after `NORMAL`?

This information is important:

> Where did you get this font, and how did you install it?

> Does this font display properly in other applications?

**Comment by blayz3r** [comment] 2020-09-09 21:36
![image](https://user-images.githubusercontent.com/12205650/92657392-befc3b80-f2c2-11ea-8e41-efeaeaeb99dd.png)

The rendering issue is more that the font doesn't look solid:
**NEOVIM:**
![image](https://user-images.githubusercontent.com/12205650/92657246-7a70a000-f2c2-11ea-9371-d90247662f09.png)
**GVIM:**
![image](https://user-images.githubusercontent.com/12205650/92657263-852b3500-f2c2-11ea-8404-39f0688b6480.png)

**Comment by jgehrig** [comment] 2020-09-09 21:58
Again, this information is important:
> Where did you get this font, and how did you install it?

This is helpful for me, it is much hard to solve an issue when I cannot reproduce it myself.

> Does this font display properly in other applications?

Based on your screenshots above, I would guess: Yes, this displays properly in gVim.

**Comment by jgehrig** [comment] 2020-09-09 21:59
> The rendering issue is more that the font doesn't look solid:

You'll have to be more specific. Sorry, the issues isn't obvious to me...

Is this an anti-aliasing problem? Something else?

**Comment by blayz3r** [comment] 2020-09-10 02:03
I think it's a direct X issue, the fonts are just blurry and not sharp

Below are the GVIM settings
```vim
"Use Directx rendering
set rop=type:directx,gamma:1.0,contrast:0.5,level:1,geom:1,renmode:4,taamode:1

**Comment by jgehrig** [comment] 2020-09-10 05:15
No, I don't think that is the issue.

**Comment by wsdjeg** [comment] 2020-09-19 13:11
![image](https://user-images.githubusercontent.com/13142418/93668033-92170800-fabc-11ea-973e-f2f19b8cf382.png)


everything work well for me,  I am using the latest version of neovim.

**Comment by blayz3r** [comment] 2020-09-19 22:27
> ![image](https://user-images.githubusercontent.com/13142418/93668033-92170800-fabc-11ea-973e-f2f19b8cf382.png)
> 
> everything work well for me, I am using the latest version of neovim.

I am using windows, how do you make the borders black

**Comment by jgehrig** [comment] 2020-10-03 16:32
Not clear what the issue is here. Marking as Closed.

If an issue can be clearly documented, feel free to re-open.

**Closed by jgehrig** 2020-10-03 16:32 UTC
