### ISSUE TITLE
finger-scrolling on a touchpad is too fast

### ISSUE THREAD

**Issue by hypercubelet** [equalsraf/neovim-qt#534] opened 2019-04-10 13:13 UTC
Scrolling a buffer with a mouse wheel scrolls 3 lines as expected, but a two-finger scroll on a touchpad scrolls by 30, 50, 100 lines or more at a time, making it unusable on a laptop.

**Comment by equalsraf** [comment] 2019-04-13 18:10
I can confirm this in Linux, but not on Mac OS X which not too surprising since they use different methods for this.

Possibly related issues upstream

- https://bugreports.qt.io/browse/QTBUG-56075?attachmentSortBy=dateTime
- https://bugreports.qt.io/browse/QTBUG-49024?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel&showAll=true

So it seems Qt has an issue with devices that provide high resolution scrolling, but are being used with the low resolution api.

**Comment by vivichrist** [comment] 2020-05-21 03:09
Please tell me there is a workaround?

**Comment by jgehrig** [comment] 2020-05-21 03:15
See Pull Request #630

Currently this change is only available in `master`, so you will have to build from source or wait until the next release.

**Comment by equalsraf** [comment] 2020-07-01 22:55
The PR for this has been merged and is available in the latest version, resolving.

**Closed by equalsraf** 2020-07-01 22:55 UTC
