### ISSUE TITLE
"nvim-qt --nofork  +mak" causes nvim-qt to hang ; the same with nvim, gvim, or :mak inside nvim-qt is fine

### ISSUE THREAD

**Issue by shlomif** [equalsraf/neovim-qt#333] opened 2017-09-20 21:39 UTC
Hi!

I am using nvim-qt built from source on Mageia Linux v7 x86-64 with latest git master nvim and nvim-qt. ( gcc-7.2.1-20170831.1.mga7 and lib64qt5core-devel-5.9.1-8.mga7 ). The command in the subject line causes nvim to hang whether or not there is a makefile.

```
shlomif[fcs]:$trunk/fc-solve/B$ nvim-qt --nofork  +mak
Qt: Session management error: Could not open network socket
Request 1 timed out: 44
Neovim fatal error "Neovim is taking too long to respond"
shlomif[fcs]:$trunk/fc-solve/B$ 
```

**Comment by equalsraf** [comment] 2017-09-20 22:26
mmm, i cannot reproduce here. What happens if you do?

    nvim-qt --nofork -- -u NONE +mak

If it works then this is a duplicate of https://github.com/equalsraf/neovim-qt/issues/78

**Comment by shlomif** [comment] 2017-09-21 07:43
@equalsraf : thanks for returning to me. Your command appears to give me the same issue:

```
shlomif[fcs]:$trunk/fc-solve/B$ nvim-qt --nofork -- -u NONE +mak
Qt: Session management error: Could not open network socket
Request 1 timed out: 44
Neovim fatal error "Neovim is taking too long to respond"
Request 2 timed out: 44
Neovim fatal error "Neovim is taking too long to respond"
Request 2 timed out: 44
Neovim fatal error "Neovim is taking too long to respond"
Request 2 timed out: 44
Neovim fatal error "Neovim is taking too long to respond"
shlomif[fcs]:$trunk/fc-solve/B$ 
```

**Comment by equalsraf** [comment] 2017-09-21 10:03
Ok I can reproduce now, it does not seem to happen with versions before 82ea7d10048df2fd42cf7457f803d45fffa180bd, but that is probably only a side effect of feeding the focus event as an input.

This problem usually means nvim is blocked waiting for user input, I assume because of the pager on :mak is waiting for an ENTER press (but from testing it seems it might not be the pager).

We can verify this is #78 with the python client

```python
from neovim import attach
nvim = attach('child', argv=["nvim", "--embed", '+mak'])
nvim.ui_attach(100, 100, True)
# this last call will block and never return
# you can test a bit by adding a few calls to nvim.input('<Space>') before the attachment
```

**Comment by shlomif** [comment] 2017-09-21 10:50
@equalsraf : thanks for the investigation and the information.

**Comment by equalsraf** [comment] 2017-09-25 08:34
Closing as duplicat of #78

**Closed by equalsraf** 2017-09-25 08:34 UTC
