### ISSUE TITLE
Ctrl+Caps Lock inserts dollar sign

### ISSUE THREAD

**Issue by unclechu** [equalsraf/neovim-qt#199] opened 2016-10-16 11:45 UTC
Why `Ctrl`+`Caps Lock` inserts dollar sign?

I'm actually using keyboard hack, and real `Caps Lock` enables by pressing both controls, so it means when `Caps Lock` is pressed `Control` keys isn't released yet. I could add release-events triggering before triggering caps lock to my hack app, but I guess this behavior of **neovim-qt** isn't right, don't you think?

P.S. I checked this without my app, just pressing really mapped caps lock and control key.

**Comment by equalsraf** [comment] 2016-10-16 16:06
Confirmed Ctrl+Caps inserts **$**, more acurately **\<C-$\>** is being sent, even though the key event text is empty.

A wrong assumption seems to be made in input.cpp about the key code, e.g. for this particular case

```diff
diff --git a/src/gui/input.cpp b/src/gui/input.cpp
index c5b4d6f..e584b47 100644
--- a/src/gui/input.cpp
+++ b/src/gui/input.cpp
@@ -167,6 +167,8 @@ QString InputConv::convertKey(const QString& text, in
t k, Qt::KeyboardModifiers
                        QList<Qt::Key> keys = { Key_Control, Key_Alt, Key
_Cmd };
                        if (keys.contains((Qt::Key)k)) {
                                return QString();
+                       } else if (k == Qt::Key_CapsLock){
+                               return QString();
                        } else {
                                // key code will be the value of the char (hopefully)
                                c = QChar(k);
```

But we should probably check whats happening on Mac OS first.

**Comment by shlomif** [comment] 2020-01-27 15:27
Now it seems that in `nvim-qt -- -u NONE` on xfce on fedora 31 x86-64 capslock without a control also inserts a dollar sign. kate, and nvim handle it fine.

**Comment by shlomif** [comment] 2020-01-27 15:44
The bad symptoms disappear after I apply this forward ported patch of the one in an earlier comment:

```diff
diff --git a/src/gui/input.cpp b/src/gui/input.cpp
index 5e44293..7858a69 100644
--- a/src/gui/input.cpp
+++ b/src/gui/input.cpp
@@ -166,6 +166,8 @@ QString convertKey(const QKeyEvent& ev) noexcept
 
 	if (specialKeys.contains(key)) {
 		return ToKeyString(GetModifierPrefix(mod), specialKeys.value(key));
+	} else if (key == Qt::Key_CapsLock) {
+		return QString();
 	}
 
 	// The key "<" should be sent as "<lt>"
```

I hereby put my changes under [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/)

**Comment by jgehrig** [comment] 2020-01-27 15:52
@shlomif 

What version of `neovim-qt` are you running? If you are not running the latest nightly from `master`, can you please build it and re-try. There have been some input layer changes recently.

If the issue still reproduces from `master`, can you please provide the output (un-commented lines) from 98d361f9333c206287ee368fdc3c4f4d92b144a5.

The patch you mention is likely the correct fix. However we should do some cross-platform validation, and write a UnitTest.

Thanks!

**Comment by shlomif** [comment] 2020-01-27 17:01
@jgehrig : I am running commit d87353c16a59c6e412a35e3e66716e5649fecb26
 from git master. I uncommented lines, rebuilt and reinstalled, but where am  I supposed to view the output?

**Comment by jgehrig** [comment] 2020-01-27 17:18
Thanks! On closer inspection of you diff, I can see you have the latest changes...

Did you do a `Release` build? You will need a `Debug` build to get the output.

With a Debug build, the messages appear on `stdout` for all platforms except [Windows](https://github.com/equalsraf/neovim-qt/wiki#i-cant-see-debug-messages-in-windows).

You should see a `QKeyEvent` printed on the terminal every time you press a key. I'm curious about the format of the `Key_CapsLock` event and any of the modifier key events leading up to it.

**Comment by shlomif** [comment] 2020-01-27 18:28
@jgehrig : I now did a Debug build, but I still cannot see any diagnostics on the invoking terminal. I tried reenabling everything  in kdebugdialog5, but it had no effect either.

**Comment by jgehrig** [comment] 2020-01-27 20:22
Don't worry about it. I am not sure what is going wrong with `qDebug` in your case.

I can reproduce the issue on one of my machines, and that is enough to generate the `QKeyEvents` needed to write tests. I will try to post a Pull Request for this issue later this evening.

Thanks for your help!

**Comment by shlomif** [comment] 2020-01-27 20:39
On Mon, 27 Jan 2020 12:22:23 -0800
John Gehrig <notifications@github.com> wrote:

> Don't worry about it. I am not sure what is going wrong with `qDebug` in your
> case.
> 
> I can reproduce the issue on one of my machines, and that is enough to
> generate the `QKeyEvents` needed to write tests. I will try to post a Pull
> Request for this issue later this evening.
> 
> Thanks for your help!
> 

Thanks, John and - you're welcome.

-- 

Shlomi Fish       https://www.shlomifish.org/
https://youtu.be/xZLwtc9x4yA - Anime in Real Life!! (Parody)

Between truth and the search for truth, I opt for the second.
    — Bernard Berenson (Unsourced via fortune-mod)

Please reply to list if it's a mailing list post - http://shlom.in/reply .

**Comment by equalsraf** [comment] 2020-01-28 21:58
PR merged into master.

**Closed by equalsraf** 2020-01-28 21:58 UTC
Labels: input

**Comment by shlomif** [comment] 2020-01-29 07:22
Thanks @equalsraf and @jgehrig !
