### ISSUE TITLE
Cursor disappear when lines are moved when getting to top/bottom borders

### ISSUE THREAD

**Issue by facundobatista** [equalsraf/neovim-qt#649] opened 2020-02-22 14:14 UTC
In any long enough file (more than the window height), when I get 3 lines before the bottom of the window (because I have `set scrolloff=3`), and press the down key, the lines of the buffer go one line up, which is the perfect behaviour for the scrolloff setting.

The problem is that at that moment the cursor disappears.

The same happens when the scroll goes up.

I created [a small video](https://github.com/equalsraf/neovim-qt/files/4239440/disapp-cursor.mp4.gz) to show this better.

**Comment by jgehrig** [comment] 2020-02-22 14:49
I have noticed similar behavior too.

Does this reproduce with `nvim` terminal? What version of `nvim`/`nvim-qt`?

You should also try this scenario with `:set guicursor=`. There have been some cursor changes recently (if you built from master).

**Comment by facundobatista** [comment] 2020-02-27 01:03
With nvim in the terminal, it behaves correctly (cursor is always there).

Doing `:set guicursor=` does not affect these behaviours.

Versions:

```
NVIM-QT v0.2.14.0
Build type: Release
Compilation: -Wall -Wextra -Wno-unused-parameter -std=c++11 -Wfatal-errors
Qt Version: 5.13.2
Environment: 
  nvim: nvim
  args: --cmd set termguicolors
  runtime: 

NVIM v0.4.3
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-9a287301-34f2-4b86-92e3-462594f51f36

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info

```

**Comment by jgehrig** [comment] 2020-03-02 04:09
I cannot reproduce this issue with a minimal configuration.

From your video, it looks like you are not using a minimal configuration. Can you eliminate options until you arrive at a minimal repro scenario?

**Scenario Steps:**
1. Open neovim-qt: `nvim-qt -- -u minimal.vim 1000.txt`
2. Go to line 500 `:500`
3. Scroll Up/Down with `j` and `k`
4. Scroll Up/Down with mouse wheel.

[1000.txt](https://github.com/equalsraf/neovim-qt/files/4273378/1000.txt)
[minimal.vim](https://github.com/equalsraf/neovim-qt/files/4273381/minimal.vim.txt)

![Peek 2020-03-01 23-02](https://user-images.githubusercontent.com/11207308/75644601-cf937100-5c10-11ea-9e16-d763b53ea22b.gif)

**Comment by facundobatista** [comment] 2020-03-10 19:53
This report was initiated based on the behaviour I had on my desktop. Last week I went to my laptop and found that there this problem didn't show up! 

Both desktop and laptop share the init config files, but `neovim-qt` was compiled at different times.

So I went and `git pull` to get latest, compiled, and found that this problem appeared! So I went back to the commit that was in the laptop (`a5e126e2f755d1423a33b26bbea663359aaa0455`), compiled it, and the problem went away! Just to re-verify it, I pulled again to get latest, compiled, and the problem was there again.

So, to summarize:

- Commit `964a2a6df8408516c49fbc23a146fe7602ffa31b` shows the problem

- Old commit `a5e126e2f755d1423a33b26bbea663359aaa0455` is good.

In both cases I'm running it like

    bin/nvim-qt -- -u NONE ~/temp/testvim-incsearch.txt

**Comment by jgehrig** [comment] 2020-03-13 07:15
I don't have any great ideas...

Maybe identifying the breaking commit with your full config will help provide some additional insight?

You could try something like:
```
git bisect start
git bisect good a5e126e2f755d1423a33b26bbea663359aaa0455
git bisect bad 964a2a6df8408516c49fbc23a146fe7602ffa31b
```

I'm also assuming this is NOT a GuiScrollBar build... I have seen similar issues there (now fixed).

**Comment by facundobatista** [comment] 2020-03-13 21:21
This is also related to `ext_linegrid`!!! with the config you indicated in [here](https://github.com/equalsraf/neovim-qt/issues/648#issuecomment-598468713) (not using `ext_linegrid`) the problem just disappears!!

**Comment by jgehrig** [comment] 2020-03-13 21:40
To summarize the information above, we know:
1. This issue only appears while `ext_linegrid` is enabled.
2. This issue DOES NOT appear for `nvim-qt -- -u NONE`
3. This issue DOES appear from `nvim-qt` with your full vimrc config.

Correct?

I think we still need more information... Can you figure out which part of your full configuration causes this and create a minimal vimrc, `minimal.vim`?

I usually perform a "binary search" of my vimrc, commenting roughly half of it each time until I can find the offending setting/plugin.

I would guess the issue is related to `grid_scroll`. I'm still not sure if the issue is upstream or in our implementation.

**Comment by facundobatista** [comment] 2020-03-25 23:31
Let me summarize it a little differently:

- if I enable `ext_linegrid`, the problem appears with my full config, and all is fine with `-- -u NONE`
- if I disable `ext_linegrid`, it's always fine no matter the config

Reducing the configuration, the problem is still there with the following `minimal.vim` (and of course `ext_linegrid` enabled):

```
call plug#begin("~/.config/nvim/plugged")
Plug 'vim-airline/vim-airline'
call plug#end()
set scrolloff=3
```

Hope this helps. I tried to nail down the responsible code *inside* the airline plugin, but couldn't do it.

**Comment by jgehrig** [comment] 2020-03-26 01:59
> Hope this helps. I tried to nail down the responsible code inside the airline plugin, but couldn't do it.

No worries, this is exactly what I was looking for! :smile:

I think the problem is with the following snippet:
https://github.com/equalsraf/neovim-qt/blob/964a2a6df8408516c49fbc23a146fe7602ffa31b/src/gui/shell.cpp#L373-L376

I can observe different units for these two regions. The cursor is in pixels, and scroll region in cells. From a quick pass, I will guess the mismatched units worked in most cases. With your configuration and `ext_linegrid`, the luck expired.

Here is a very naive fix:
```diff
--- a/src/gui/shell.cpp Tue Feb 11 12:42:55 2020 -0500
+++ b/src/gui/shell.cpp Wed Mar 25 21:53:20 2020 -0400
@@ -1105,13 +1105,12 @@
 
        m_scroll_region = QRect(QPoint(left, top), QPoint(right, bot));
 
-       if (m_scroll_region.contains(m_cursor_pos)) {
-               // Schedule cursor region to be repainted
-               update(neovimCursorRect());
-       }
+       update(neovimCursorRect());
 
        scrollShellRegion(m_scroll_region.top(), m_scroll_region.bottom(),
                m_scroll_region.left(), m_scroll_region.right(), rows);
+
+       update(neovimCursorRect());
 }
 
 void Shell::paintEvent(QPaintEvent *ev)
```

I investigate further to find a fix that performs better, and runs checks with the proper units. Enough information is present already; we shouldn't schedule unnecessary UI re-paints.

**Closed** 2020-07-20 04:35 UTC
