### ISSUE TITLE
window minimum

### ISSUE THREAD

**Issue by kdurant** [equalsraf/neovim-qt#447] opened 2018-08-20 11:32 UTC
The window is always small when the neovim-qt is turned on when PC re-start

**Comment by equalsraf** [comment] 2018-08-20 12:02
Hi @kdurant. Are you using windows? If so there is already an open issue for this in https://github.com/equalsraf/neovim-qt/issues/251

**Comment by equalsraf** [comment] 2018-09-16 23:27
Closing as a duplicate of #251.

**Closed by equalsraf** 2018-09-16 23:27 UTC
