### ISSUE TITLE
Extremely slow rendering with ligatures enabled on NVidia

### ISSUE THREAD

**Issue by sid-6581** [equalsraf/neovim-qt#1025] opened 2022-11-01 13:44 UTC
I have been testing neovim-qt with various settings on my laptop with a 4k screen and integrated Intel GPU (it's a hybrid with an NVidia 3080, but that isn't used for desktop rendering), as well as my desktops with NVidia 3070 and 3090 cards.

On my laptop with the slower graphics card, running in fullscreen, neovim-qt runs great with ligatures enabled. With the exact same settings on my desktops with a much more powerful CPU and GPU, it's so slow that it's unusable with ligatures enabled. It seems to slow down everything. Opening neovim-qt takes seconds with ligatures enabled, opening a small file takes seconds, etc. When it's a larger file that fills the entire screen, I can see it being redrawn in chunks. None of these are problems on my laptop with the integrated Intel GPU.

This is counter-intuitive to me, since I'd expect the faster GPU/CPU to be much more performant.

I also have this problem if I start with `-u NONE` and manually do `:GuiRenderLigatures 1`, so it's not related to any settings or plugins I have.

I am on Windows 11 with the latest NVidia drivers.

**Comment by jgehrig** [comment] 2022-12-08 16:43
@sid-6581

This sounds like it could be a Qt related graphics driver bug... Do you have the output of `nvim-qt --version`?

It would be helpful to understand the Qt and Neovim Qt versions. Bumping the versions of both may help.

I'm doubtful there is much we will be able to do here:
 - I won't be able to reproduce this issue (it is hardware specific).
 - We're calling Qt APIs to handle ligature rendering, the bug is likely to be in their code.

**Comment by sid-6581** [comment] 2022-12-12 06:11
Thanks for the reply! Here is the version info:

![image](https://user-images.githubusercontent.com/28602336/206972028-1efa20eb-a34a-4bdb-8096-91338ba63b5c.png)

I don't mind compiling and doing some profiling on my machine to try to narrow it down. I'll see if I can get a chance to do that next week since this doesn't seem to be a known issue.

**Comment by jgehrig** [comment] 2022-12-13 18:54
> I don't mind compiling and doing some profiling on my machine to try to narrow it down.

This would be very helpful!

**Comment by jgehrig** [comment] 2023-05-01 23:55
I still cannot reproduce this issue, and it sounds like a rendering Qt bug specific to your platform and graphics hardware.

If anyone can provide a performance profile, I'd be happy to investigate.

Otherwise, I'm marking this as Closed - No Repro.

**Closed by jgehrig** 2023-05-01 23:55 UTC
