### ISSUE TITLE
Crash while entering content

### ISSUE THREAD

**Issue by cnfczn** [equalsraf/neovim-qt#1014] opened 2022-09-07 09:28 UTC
```
flameshot[13422]: QPainter::begin: Paint device returned engine == 0, type: 2
flameshot[13422]: QPainter::setRenderHint: Painter must be active to set rendering hints
flameshot[13422]: QPainter::setCompositionMode: Painter not active
flameshot[13422]: QPainter::translate: Painter not active
flameshot[13422]: QPainter::setPen: Painter not active
flameshot[13422]: QPainter::setBrush: Painter not active
flameshot[13422]: QPainter::setBrush: Painter not active
flameshot[13422]: QPainter::begin: Paint device returned engine == 0, type: 2
flameshot[13422]: QPainter::setRenderHint: Painter must be active to set rendering hints
flameshot[13422]: QPainter::setCompositionMode: Painter not active
flameshot[13422]: QPainter::translate: Painter not active
flameshot[13422]: QPainter::setPen: Painter not active
flameshot[13422]: QPainter::setBrush: Painter not active
flameshot[13422]: QPainter::setBrush: Painter not active
flameshot[13422]: QPainter::begin: Paint device returned engine == 0, type: 2
flameshot[13422]: QPainter::setRenderHint: Painter must be active to set rendering hints
flameshot[13422]: QPainter::setCompositionMode: Painter not active
flameshot[13422]: QPainter::translate: Painter not active
flameshot[13422]: QPainter::setPen: Painter not active
flameshot[13422]: QPainter::setBrush: Painter not active
flameshot[13422]: QPainter::setBrush: Painter not active
kernel: nvim[26994]: segfault at 4a2d9440 ip 00007f7769ed22c4 sp 00007ffc363f5780 error 4
systemd[1]: Started Process Core Dump (PID 40691/UID 0).
systemd-coredump[40692]: elfutils disabled, parsing ELF objects not supported
systemd-coredump[40692]: [🡕] Process 26994 (nvim) of user 1008 dumped core.
systemd[1]: systemd-coredump@1-40691-0.service: Deactivated successfully.
nvim-qt[2587]: Neovim fatal error "The Neovim process has crashed"
flameshot[13422]: QPainter::begin: Paint device returned engine == 0, type: 2
flameshot[13422]: QPainter::setRenderHint: Painter must be active to set rendering hints
flameshot[13422]: QPainter::setCompositionMode: Painter not active
flameshot[13422]: QPainter::translate: Painter not active
flameshot[13422]: QPainter::setPen: Painter not active
flameshot[13422]: QPainter::setBrush: Painter not active
flameshot[13422]: QPainter::setBrush: Painter not active
```

It doesn't happen every time. It's an accident

**Comment by jgehrig** [comment] 2022-09-24 14:15
It looks like the issue here is the `nvim` process crashing out from under us. I'd guess this is an upstream issue in Neovim.

However, more information is required to understand the issue. You'll either need a crash dump with callstack or a set of steps that consistently reproduces the issue (or at the very least triggers it semi-consistently). Without more information, there isn't much we can do.

Closing for now -- feel free to re-open with more details (version, install type, crash dump, etc) or a consistent way to reproduce the issue.

**Closed by jgehrig** 2022-09-24 14:15 UTC
