### ISSUE TITLE
Can't start maximized

### ISSUE THREAD

**Issue by cdvv7788** [equalsraf/neovim-qt#83] opened 2015-12-20 15:13 UTC
I am using neovim with qt-neovim (linux arch). On gvim i could launch a maximized window with:

    if has("gui_running")
        set lines 999 columns 999
    endif

That is not working now tho. I tried removing the condition with no success.
Is there any way i can achieve that?

**Comment by cdvv7788** [comment] 2015-12-20 16:30
After restarting somehow it is reading the command, however it doesn't restrict the max size to my screen size, it creates a giant one.

**Comment by equalsraf** [comment] 2015-12-20 21:49
if has("gui_running") is not reliable right now (see neovim/neovim#3646)

> however it doesn't restrict the max size to my screen size, it creates a giant one.

This is strange, should not happen, will have a look.

**Comment by cdvv7788** [comment] 2015-12-20 21:55
Yeah, i read on some other issues that has("gui_running") is not reliable, so i tried without it too.

**Comment by equalsraf** [comment] 2015-12-20 22:02
The problem is vimrc will likely be processed before the gui even starts, so its all a matter of timing.

**Comment by cdvv7788** [comment] 2015-12-24 21:11
Any workaround for this? Anything i can help with on this issue?

**Comment by equalsraf** [comment] 2016-03-14 18:23
@cdvv7788 not forgotten, I've got something in #109

**Comment by equalsraf** [comment] 2016-03-31 17:45
#109 was merged, --maximized should start a maximized window. From what we have seen so far using set lines/columns is not a good way to do this, but we can finally start looking at other ways to do this.

**Comment by khalidchawtany** [comment] 2016-04-01 21:36
leaving a comment to be notified of anything new on toggle full screen command :)

**Comment by equalsraf** [comment] 2016-04-04 15:14
Starting to look at this on #114  ([script](https://github.com/equalsraf/neovim-qt/pull/114/files#diff-b996c9a7410476c5ddf91c4b00121b01R1))
Any idea what are the right semantics for this type of stuff

- are these supposed to be functions like `foreground()` or actual commands?
- Do we want toggle or explicit commands `GuiMaximize` vs `GuiMaximizeToggle`
- Have no idea how we are supposed to share state, ideally set g:GuiIsMaximized (because that sounds easy enough :D)

**Comment by equalsraf** [comment] 2016-04-05 10:36
Pushed something into #114 

If testing directly from a source build use this for now
```
bin/nvim-qt -- --cmd "set rtp+=../runtime/ | runtime autoload/nvim_gui.vim"
```

init.vim looks like this

```vim
" We can check first if the following commands are available, but the last one is just a var anyway
if exists('g:Gui')
    Guifont DejaVu Sans Mono:h15

    " Starts in fullscreen, Maximized should work too (untested)
	let g:GuiWindowFullScreen=1
endif
```

**Closed** 2016-04-19 15:52 UTC

**Comment by equalsraf** [comment] 2016-04-19 16:08
From #114 `call GuiWindowMaximized(1)` to set as maximized. The current state in g:GuiWindowMaximized.

@khalidchawtany for fullscreen its the same, just replace with `GuiWindowFullScreen`

**Comment by khalidchawtany** [comment] 2016-04-19 21:25
Lovely,  Thanks. :+1:

**Comment by jdhao** [comment] 2019-01-17 11:58
Using `call GuiWindowMaximized(1)` command inside nvim-qt works great. Can we also use it inside `ginit.vim`?

**Comment by equalsraf** [comment] 2019-01-17 21:23
Hi @jdhao. It should work inside ginit.vim as well. Are you having issues with it.

**Comment by jdhao** [comment] 2019-01-18 02:02
@equalsraf  It works. Thanks!

**Comment by dseeni** [comment] 2020-03-29 02:58
How do I go about discovering such handy commands for nvim-qt? Such as GuiFullScreen and GuiWindowMaximized? So useful to know that I can toggle inside of Vim and it works in init.vim!!

**Comment by equalsraf** [comment] 2020-04-02 11:07
@dseeni these are described in the docs. Just call `:h nvim-gui-shim`.

**Comment by dseeni** [comment] 2020-04-10 05:18
@equalsraf, 
hmm, odd.. I can't get the docs on windows 8.1 .. but clearly the commands work...

**Comment by equalsraf** [comment] 2020-04-10 22:07
>  Is there any advantage for me compiling it? I'm just using an executable from the releases page...

Same as every other piece of software, you get to test the newest changes and broken bits before anyone else :D.
