### ISSUE TITLE
Dead keys are broken in Windows for some keyboard layouts

### ISSUE THREAD

**Issue by equalsraf** [equalsraf/neovim-qt#270] opened 2017-05-02 16:46 UTC
- Pressing a dead key followed by space, produces a space instead of the expected key
- Pressing the dead key twice produces the expected key.

### References

- https://github.com/equalsraf/neovim-qt/issues/179#issuecomment-244522196
- https://github.com/neovim/neovim/issues/6642
- http://stackoverflow.com/questions/28793356/qt-and-dead-keys-in-a-custom-widget
- https://groups.google.com/forum/#!topic/leo-editor/re5fieBHRgw

**Comment by equalsraf** [comment] 2017-05-07 11:33
Builds with some extra logged info for this at https://ci.appveyor.com/project/equalsraf/neovim-qt/build/1102/job/sso8sx24gk5ghq9w/artifacts but so far a dead key produces two keypress events with `~`

**Comment by yuntan** [comment] 2017-07-21 13:08
I cannot input "*" on jp106 keyboard ("*" is inputted by "shift :"). My problem may be related to this issue.

**Comment by yuntan** [comment] 2017-07-23 08:03
I just confirmed that I can't reproduce the problem that I commented above on master (https://ci.appveyor.com/project/equalsraf/neovim-qt/build/job/3dpsatte6lr94fmv/artifacts). Above comment is on the version that is bundled in neovim v0.2.0.

**Comment by w1mb0r** [comment] 2017-12-14 12:31
tested this again on NVIM v0.2.3-234-gb0e9132cf and nvim-qt.exe dating 06/09/2017 17:58
issue still exists

**Comment by w1mb0r** [comment] 2018-09-06 13:59
I tested this again on nvim-qt dating  2018-08-26 with nvim v0.3.2-402-ge30ccd56d and using an azerty keyboard.
This issue still occurs.
The affected keys are:
- ¨
- ^
- ´
- `
- ~

If i type such such dead key followed by the space bar, I should get the character but nothing appears.
I need to type the dead key twice, then I get the character twice and delete the redundant character.

**Comment by AssertFailure** [comment] 2018-12-12 11:09
My fix (https://github.com/AssertFailure/neovim-qt/tree/fix-270) to the missing dead keys is to not ignore Event's text when the actual key is a special key. It seems to work fine, but it needs a suboptimal special handling for special keys which would produce unintended text as well. I noticed that only Delete key did that on my setup, but I'm not certain if that depends on the key layout or something.

**Comment by TheSandvichMaker** [comment] 2019-06-23 16:31
This is still an issue for me on on the latest build at this time (23/06/2019), nvim v0.3.5-11-g1060bfd03, using the US International layout. So long as there isn't a fix, using nvim-qt would be very cumbersome for me (which is a shame, since I want to use it!)

**Comment by KayzzenD** [comment] 2019-12-24 00:29
Neovim Qt is much nicer than nvim on CMD, at least on Windows it is. I will use gvim for now on Windows and I am monitoring this its solution.

NVIM v0.4.3
NVIM-Qt 0.2.14.0

**Comment by markstos** [comment] 2020-01-29 14:38
In my case I found that the issue was that I was using a QMK-powered keyboard and my asterisk key was sending a "Numpad Asterisk". I updated the firmware to send a "Shifted Punctuation Asterisk" instead and that resolved the issue with Neovim 0.3.8.

**Comment by lucasteles** [comment] 2020-03-20 14:47
Same problem here ☹

**Comment by matteocoder** [comment] 2021-07-23 08:02
I can confirm that the issue still exists in the latest stable build.

**Comment by EdwinWenink** [comment] 2021-11-13 12:02
Same issue persists on NVIM 0.5.1 nvim-qt

**Comment by solispauwels** [comment] 2022-05-24 14:07
I just install Neovim because of the Copilot plugin that is not available on Gvim.
I am starting to hate Neovim with this kind of shitty issues.
I also needed to remap Y and P

**Comment by pvin100** [comment] 2022-06-04 16:16
This issue still exists on nvim 0.7.0 / nvim-qt 0.2.16.1, not able to use nvim-qt on windows with United States-International kb layout.
Not possible to enter an "é" or an "è "

**Comment by solispauwels** [comment] 2022-06-07 07:08
My biggest problem is ' ('+ space) and " ("+ space)  Have someone found a work arround? I tried to do remaps without success.

**Comment by solispauwels** [comment] 2022-06-07 15:11
Also, when you create a mark on a file, example: **m + a**, then you can return to the mark with **' + a**, this is also impacted by this issue, I cannot return to my marks on my english international keyboard while the **'** key is a dead key. and doing double **''** will not work here (as it was the work arround to write simple **'** in code)

**Comment by pvin100** [comment] 2022-06-07 15:29
> My biggest problem is ' ('+ space) and " ("+ space) Have someone found a work arround? I tried to do remaps without success.

Does not seem to have any work arround for neovim-qt. For now, you can try to use an alternate GUI front-end like neovide which does not suffer from this issue

**Comment by jgehrig** [comment] 2022-06-07 15:31
@solispauwels @pvin100 

I'm sorry to hear you're frustrated and having issues with the input layer. Hopefully we can fix these issues!

However, I need more information to fix these problems. There are large variations between platforms and keyboard localizations.

Here's what I need:
1. Test using a build from the latest commit, https://github.com/equalsraf/neovim-qt/actions/runs/2397296878
2. Note your platform (Windows, Mac, Linux) and keyboard localization.
3. List the keys you press, what appears and what you expect to appear. Be explicit.

If you have the ability to build from source, the following is extra-helpful:
1. Un-comment [these lines of code](https://github.com/equalsraf/neovim-qt/blob/6291e6144b9b63b2fe9a650db50e03d04c2e3074/src/gui/shell.cpp#L1368-L1369).
2. Build in Debug: `cmake -GNina -DCMAKE_BUILD_TYPE=Debug`
3. Open neovim-qt with `nvim-qt -- -u NONE`
4. Pressing a minimal number of keys, perform the problematic key sequence.
5. Paste the log output into this  bug. On Windows, there is an [extra step to get the logs](https://github.com/equalsraf/neovim-qt/wiki#i-cant-see-debug-messages-in-windows).

**Comment by pvin100** [comment] 2022-06-07 17:50
@jgehrig 
I have tested build from [](https://github.com/equalsraf/neovim-qt/actions/runs/2397296878) and issue seems to be solved for me on latest windows 10, with qwerty intl layout

**Comment by jgehrig** [comment] 2022-06-07 18:03
@pvin100

Thanks! I'm glad to hear the issues are resolved with the latest build.

I need to do a release soon, so it is easier to pick up the fixes...

**Comment by pvin100** [comment] 2022-06-07 18:14
@jgehrig 
Sure, you should do a new release as soon as possible, previous release (as bundled with neovim for windows) is totally unusable for me. Thanks for your work on this project

**Comment by jgehrig** [comment] 2022-06-07 18:58
@pvin100 

> Thanks for your work on this project

Thanks for the kind words! :)

I've filed a bug to track generating a new release: #988 

> 
    Pressing a dead key followed by space, produces a space instead of the expected key
    Pressing the dead key twice produces the expected key.

If my understanding is correct, this issue is fixed. We no longer have the 'Dead-Key' issues, correct?

It sounds like we should close this issue, since it is resolved in `master`?

**Comment by pvin100** [comment] 2022-06-08 06:54
I have the same understanding, I think you can close this issue

**Comment by solispauwels** [comment] 2022-06-08 14:25
Hello, After testing last commit, On my side I am still experiencing issues with maks jump ('{a-z} :help mark). but ' + space is working now.
Does some one still knows a workarround for marks? [pvin100](https://github.com/pvin100) I tested Neovide wich is very nice, thanks for the advice. Indeed out of the box it have no issues with keyboard.

**Comment by pvin100** [comment] 2022-06-08 15:12
@solispauwels 
Will try on windows later this day but jump to mark is expected to be  [ ' ] followed by [space] and next mark letter

**Comment by jgehrig** [comment] 2022-06-08 15:28
@pvin100

Sounds good, I'm going to close this issue.

@solispauwels 

Please open a new issue, and we will try to fix those input bugs.

A few things to keep in mind when filing bugs:
1. Please keep things objective, using negative language doesn't help anyone.
2. Please be specific with the issues you are having. I need to be able to reproduce them to fix them.
  a. What platform using? Ex) Windows, Linux, MacOS
  b. What keyboard layout? Ex) US, German, Spanish, etc
  c. What is the specific sequence of keys you are pressing? What happens? What did you expect to happen?

Let's move this conversation over to the new bug. Thanks!

**Closed by jgehrig** 2022-06-08 15:28 UTC
Labels: input

**Comment by solispauwels** [comment] 2022-06-08 17:10
[pvin100](https://github.com/pvin100) I am using US-English keyboard with the international layout. 
No, the mark is not expected to be [ ' ] followed by [space] and next mark letter. At least not in regular vim or gvim.

**Comment by pvin100** [comment] 2022-06-08 19:08
@solispauwels It does not relate with vim but with the international layout. With this layout ['] and [`] act as dead keys to be used with other keys combinations. You have to use space to ask the OS to send the regular qwerty symbol to the app. I just have tested the 2 jumps styles with latest build, it works fine

**Comment by solispauwels** [comment] 2022-06-08 19:42
That is no true for regular Gvim without any plugin or remap on Windows or even on Linux, with an international US-English keyboard. 

You can do:

Windows:
```sh
& 'C:\Program Files (x86)\Vim\vim82\gvim.exe' --noplugin -u NONE -N
```

Linux:
```sh
$ gvim --noplugin -u NONE -N
```

Then add a mark **m + a**
Then retrive the mark with simply **' + a**

No need to hit an space on between. Indeed this can be may the case in some terminals but not in GUI mode. But here we are on a GUI repository talking about GUI issues. This is not related to you OS dead keys binding.

I use Gvim for more then 15 years and I'd never encounter issues such as this one, nor on Windows or Linux. I encounter that only now when I am trying to move to Neovim with Neovim-gt. and Now I have guys saying me that is normal to press space after ' because of the OS (Crazy).

**Comment by jgehrig** [comment] 2022-06-08 20:04
> Now I have guys saying me that is normal to press space after ' because of the OS (Crazy).

Nobody said this, and ranting does not help anyone. It helps to be kind when asking for free help with open source software.

If you want this problem solved please open a new issue with detailed steps on how to reproduce the problem, what you observe, and what you expect to occur.

I'm not familiar with your keyboard layout or configuration, so you'll need to be detailed.

**Comment by pvin100** [comment] 2022-06-08 20:22
@solispauwels 
You probably know better but no need to be so rude 

@jgehrig 
I have made some more tests and so far everything is working as expected. This long lasting issue seems definitively over, thanks

**Comment by solispauwels** [comment] 2022-06-08 21:07
I am very sorry if I sound rude, it was no my intention. Have a nice day guys and thanks for the help, Sure, we can close this.

**Comment by kayzzen01** [comment] 2022-07-16 19:29
There is some planning to solve this problem. I used NeoVIM-QT version 0.2.17 and it still has this problem.

Here is the result of my tests:

```
VIM/gVIM : ~ + space = ~
NeoVIM   : ~ + space = ~
NeoVIM-QT: ~ + space = space
NeoVIM-QT: ~~ = ~~
```

**Comment by solispauwels** [comment] 2022-07-16 23:21
I can suggest you to use neovide which does not have this issue.

**Comment by kayzzen01** [comment] 2022-07-19 02:42
Seems like a great option. I'll test.

Thank you @solispauwels !
