### ISSUE TITLE
Don't save window position on wayland

### ISSUE THREAD

**Issue by WhyNotHugo** [equalsraf/neovim-qt#679] opened 2020-04-13 18:28 UTC
I noticed that `neovim-qt` keeps creating a config file every time I run it, in `.config/nvim-qt/window-geometry.conf`. I found this curious because I didn't configure anything; all configuration is done via `.config/nvim/config`.

I looked at it and noticed it only keeps the window size, position, etc.

Is there a way to configure it not to do this? It just annoys me that this file keeps popping up (I git-track my settings, and this keeps showing up as a new file).

Moreover, on Wayland, the client (application) has no control over window placement. That is: the compositor completely controls where the windows is positioned. So on Wayland, I see little use for the app even storing this. Could you skip saving it entirely by default on Wayland?

**Comment by jgehrig** [comment] 2020-04-13 21:05
> I noticed that neovim-qt keeps creating a config file every time I run it, in .config/nvim-qt/window-geometry.conf. I found this curious because I didn't configure anything; all configuration is done via .config/nvim/config.

Sorry for the annoyance. There isn't a way to disable those config files.

Programs creating files within `.config` is common. For example, `google-chrome` caches 1000's of files into this directory. How do you usually handle this scenario?

The storage mechanism for window size is `QSettings`. You can find the code responsible for this behavior in Pull #551.

I think this bug should be "Won't Fix", the behavior is by design.

> Moreover, on Wayland, the client (application) has no control over window placement. That is: the compositor completely controls where the windows is positioned. So on Wayland, I see little use for the app even storing this. Could you skip saving it entirely by default on Wayland?

Several platforms are supported by `neovim-qt` Wayland is the odd-man-out in this scenario. We should avoid writing platform specific logic if possible. It quickly makes testing hard.

Wayland must be give applications control of their size, right? If so, at least some of the information in this config file is still necessary.

**Comment by WhyNotHugo** [comment] 2020-04-13 21:47
> There isn't a way to disable those config files.

Would it be considerable to add one? I really dislike neovim-qt creating a second config file, just to store information that (a) it cannot use on my platform (b) I would prefer be discarded anyway.

> Programs creating files within .config is common. For example, google-chrome caches 1000's of files into this directory. How do you usually handle this scenario?

I don't use `google-chrome`. Its Linux support is very poor, and doesn't even really run properly on Wayland.

> the behavior is by design.

It does not work though; the window position is save and never used for anything (since you can't control where new windows are created anyway).

> Wayland must be give applications control of their size, right? If so, at least some of the information in this config file is still necessary.

No, it fortunately does not. On wayland the compositor controls this completely.  

This isn't always really the case on Xorg either; if running under a tiling window manager, applications can't really control their window size much either, since positioning and resizing are concepts that don't really exist for tiling WMs.

**Comment by WhyNotHugo** [comment] 2020-04-13 21:49
> There isn't a way to disable those config files.

Would it be considerable to add one? I really dislike neovim-qt creating a second config file, just to store information that (a) it cannot use on my platform (b) I would prefer be discarded anyway.

> Programs creating files within .config is common. For example, google-chrome caches 1000's of files into this directory. How do you usually handle this scenario?

I don't use `google-chrome`. Its Linux support is very poor, and doesn't even really run properly on Wayland.

However, from what I've seen in the past, it saves its cache to `.cache/chromium`. Maybe neovim-qt should save this information into `.cache`? This file is most definitely not "user configuration"; the file isn't even user-readable.

> the behavior is by design.

It does not work though; the window position is save and never used for anything (since you can't control where new windows are created anyway).

> Wayland must be give applications control of their size, right? If so, at least some of the information in this config file is still necessary.

No, it fortunately does not. On wayland the compositor controls this completely.  

This isn't always really the case on Xorg either; if running under a tiling window manager, applications can't really control their window size much either, since positioning and resizing are concepts that don't really exist for tiling WMs.

**Comment by jgehrig** [comment] 2020-04-13 22:59
> I don't use google-chrome. Its Linux support is very poor, and doesn't even really run properly on Wayland.

Chrome was an arbitrary example. My point wasn't about Chrome, it was that this behavior is very common. Applications create files in `~/.config` regularly, sometimes with one-off information.

This is common and standard behavior.

> No, it fortunately does not. On wayland the compositor controls this completely.

Interesting... I'm not very familiar with Wayland.

Yes, we tested with a tiling window manager. We didn't find any bad behavior (other than the config file), the window size just doesn't change.

> Would it be considerable to add one? I really dislike neovim-qt creating a second config file, just to store information that (a) it cannot use on my platform (b) I would prefer be discarded anyway.

Personally, I won't add it. I think it increases complexity of code/testing for little benefit.

However, if have a solution feel free to create a Pull Request. Maybe others will disagree with me, or you will change my mind with a simple fix :)

We currently use [https://doc.qt.io/qt-5/qsettings.html](QSettings) for this and other settings. I am not opposed to moving this to `.cache`, but any solution must be cross-platform. Ideally, we would use a Qt Framework abstraction.

**Comment by jgehrig** [comment] 2020-04-13 23:16
A potential solution maybe... You could locally patch `nvim-qt`?

On some distros this is easy, and others painful. Here is a patch:

```patch
diff -r 0bb7322251b6 src/gui/mainwindow.cpp
--- a/src/gui/mainwindow.cpp    Mon Apr 13 01:47:29 2020 -0400
+++ b/src/gui/mainwindow.cpp    Mon Apr 13 19:03:31 2020 -0400
@@ -405,16 +405,16 @@
 
 void MainWindow::saveWindowGeometry()
 {
-       QSettings settings{ "nvim-qt", "window-geometry" };
-       settings.setValue("window_geometry", saveGeometry());
-       settings.setValue("window_state", saveState());
+       //QSettings settings{ "nvim-qt", "window-geometry" };
+       //settings.setValue("window_geometry", saveGeometry());
+       //settings.setValue("window_state", saveState());
 }
 
 void MainWindow::restoreWindowGeometry()
 {
-       QSettings settings{ "nvim-qt", "window-geometry" };
-       restoreGeometry(settings.value("window_geometry").toByteArray());
-       restoreState(settings.value("window_state").toByteArray());
+       //QSettings settings{ "nvim-qt", "window-geometry" };
+       //restoreGeometry(settings.value("window_geometry").toByteArray());
+       //restoreState(settings.value("window_state").toByteArray());
 }
 
 }  // namespace NeovimQt
```

**Comment by jgehrig** [comment] 2020-08-06 04:35
Marking as closed since a patch/workaround is available.

If there is enough user feedback, we can consider re-opening.

**Closed by jgehrig** 2020-08-06 04:35 UTC
