### ISSUE TITLE
Issuer about show half character on status bar.

### ISSUE THREAD

**Issue by zhaozg** [equalsraf/neovim-qt#384] opened 2018-01-26 15:16 UTC
I install spacevim for nvim, and I got
![image 2](https://user-images.githubusercontent.com/542599/35446213-f63c93c2-02ee-11e8-870a-9b96f2da1f39.png)

And half character on status, please reference to https://spacevim.org/

**Comment by equalsraf** [comment] 2018-01-26 15:31
This sounds like a duplicate of https://github.com/equalsraf/neovim-qt/issues/110 or https://github.com/equalsraf/neovim-qt/issues/140. Check the discussion in the comments of https://github.com/equalsraf/neovim-qt/pull/141 we dont have a working solution.

**Comment by zhaozg** [comment] 2018-01-26 15:50
I merged trunk `tb-unicode-chars`, but show same with not patch.

**Comment by equalsraf** [comment] 2018-01-26 16:48
Ok this one seems to be different.

I also tested this in

- gvim cuts the char in half
- libvte cuts the char in half
- konsole renders it past its cell
- both vim and neovim treat this symbol as a single width char

I dont think this char is meant to be a double width char, at least both vim and nvim are consistent on this and so is libvte/konsole. I would suspect the symbols are missing from the fonts.

test snippet

```
//345
//⓿45
//❶45
//龍5
```

**Comment by zhaozg** [comment] 2018-01-27 05:06
@equalsraf I checked some font related exmaple int https://github.com/equalsraf/neovim-qt/tree/master/src/gui/shellwidget

```
> fontinfo.exe "DejaVu Sans Mono for Powerline"                     
Font family: DejaVu Sans Mono for Powerline                         
Exact match: 1                                                      
Real family: DejaVu Sans Mono for Powerline                         
Font size: 10                                                       
!  (Regular) Average char width: 8 Max char width: 17 Width(MM): 16 
!   (Italic) Average char width: 8 Max char width: 17 Width(MM): 16 
!     (Bold) Average char width: 9 Max char width: 18 Width(MM): 18 
!  (Bold+It) Average char width: 9 Max char width: 18 Width(MM): 18                                              
```
It's strange that font width is not fixed.  Maybe this is root reason.

**Comment by zhaozg** [comment] 2018-01-27 05:08
This https://github.com/equalsraf/neovim-qt/issues/266 same.

**Comment by zhaozg** [comment] 2018-01-27 05:55
@equalsraf Maybe help to you .

when utf-8 encode chinese character
```
> fontinfo.exe "DejaVu Sans Mono for Powerline"                                    
Font family: DejaVu Sans Mono for Powerline                                        
Exact match: 1                                                                     
Real family: DejaVu Sans Mono for Powerline                                        
Font size: 10                                                                      
!  (Regular) Average char width: 8 Max char width: 17 Width(MM): 16 Width(??-): 13 
!   (Italic) Average char width: 8 Max char width: 17 Width(MM): 16 Width(??-): 13 
!     (Bold) Average char width: 9 Max char width: 18 Width(MM): 18 Width(??-): 13 
!  (Bold+It) Average char width: 9 Max char width: 18 Width(MM): 18 Width(??-): 13                                                                    
```

when GBK/ASN1 encode chinese character.
```
E:\work\extra\neovim-qt\build\bin>fontinfo.exe "DejaVu Sans Mono for Powerline"
Font family: DejaVu Sans Mono for Powerline
Exact match: 1
Real family: DejaVu Sans Mono for Powerline
Font size: 10
!  (Regular) Average char width: 8 Max char width: 17 Width(MM): 16 Width(?a): 16
!   (Italic) Average char width: 8 Max char width: 17 Width(MM): 16 Width(?a): 16
!     (Bold) Average char width: 9 Max char width: 18 Width(MM): 18 Width(?a): 16
!  (Bold+It) Average char width: 9 Max char width: 18 Width(MM): 18 Width(?a): 16
Font size: 11
```

**Comment by zhaozg** [comment] 2018-01-27 07:00
Look like https://github.com/equalsraf/neovim-qt/blob/master/src/gui/shellwidget/shellcontents.cpp#L236
`c.doubleWidth` have some issue

**Comment by zhaozg** [comment] 2018-01-27 09:02
With patch https://github.com/equalsraf/neovim-qt/pull/386, neovim-qt works fine for me.
![image 4](https://user-images.githubusercontent.com/542599/35470397-da33f59a-0383-11e8-93a0-81a642a79cef.png)

**Comment by zhaozg** [comment] 2018-05-28 10:52
may be because `Qt 5.0 uses and fully supports version 6.2 of the Unicode standard.`  in  http://doc.qt.io/qt-5/unicode.html

**Closed** 2019-01-06 07:07 UTC
Labels: font
