### ISSUE TITLE
[Windows 8.1] clipboard support?

### ISSUE THREAD

**Issue by aikeru** [equalsraf/neovim-qt#123] opened 2016-05-12 17:45 UTC
Just wondering if this is something that should be tracked in this repo via an issue and hoping it's in the works... :)

**Comment by equalsraf** [comment] 2016-05-12 21:11
Not in the works, but it has popped up a couple times now

- https://github.com/neovim/neovim/issues/4726#issuecomment-218673444
- https://github.com/equalsraf/neovim-qt/issues/111#issuecomment-209291643

what exactly did you have in mind?

**Comment by aikeru** [comment] 2016-05-13 00:38
Well, hoping to be able to paste from Windows system clipboard using ```"*p``` or ```"+p``` and similarly yank to it, etc.

Instead I get an error re clipboard provider.

Is there some other way to do this with neovim-qt?

**Comment by equalsraf** [comment] 2016-05-13 08:47
@aikeru regular yank and paste commands are not specific to neovim-qt they are handled by neovim. This should already be working in Windows too.

Are you using the Neovim builds from appveyor or are you building it yourself? The builds include a win32yank.exe that handles the clipboard functions.

**Comment by aikeru** [comment] 2016-05-13 19:17
I'm using builds from appveyor and I have win32yank.exe in the same folder that nvim.exe is executing from. The specific message I get is
```
clipboard: provider is not available
E353: Nothing in register *
Press ENTER or type command to continue
```
In case it helps here's the nvim --version output
```
NVIM 0.1.1
Build type: Release
Compilation: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd6
4/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /O2 /Ob2 /D NDEBUG -DDISABLE_LOG /W3 -D_CRT_
SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DINCLUDE_GENERATED_DECLARATIONS
-DHAVE_CONFIG_H -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/
projects/neovim/deps64/usr/include -IC:/projects/neovim/deps64/usr/include -IC:/
projects/neovim/deps64/usr/include/luajit-2.0 -IC:/projects/neovim/build/src/nvi
m/auto -IC:/projects/neovim/build/include
Compiled by appveyor-vmppveyor@appveyor-vm

Optional features included (+) or not (-): -acl   -iconv    -jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/projects/neovim/INSTALL/share/nvim"
```

**Comment by BohrShaw** [comment] 2016-05-22 08:48
I got `E903: Process for command "win32yank" could not be spawned`.

**Comment by equalsraf** [comment] 2016-05-23 08:07
@BohrShaw ups, it seems win32yank.exe is a 64bit binary, will need to fix that.

**Comment by rgoliveira** [comment] 2016-08-01 18:33
Just weighing in: I just installed everything as per [Neovim's instructions for Windows](https://github.com/neovim/neovim/wiki/Installing-Neovim#windows), and the clipboard didn't work.

**To fix this**, I had to manually download the [latest release of `win32yank`](https://github.com/equalsraf/win32yank/releases/) (`v0.0.2` as of this writing) and overwrite the shipped with the Neovim Windows build.

*I should probably tell this to the neovim contributors*

**Comment by dumblob** [comment] 2016-08-01 20:37
This reminded me about my dissatisfaction with Windows programs requiring separate installation of "development" libraries like `VCRUNTIME140.dll`. Even though it's such a tiny thingie, it's quite annoying, complicating auto-(un)installations and in the first place it is not necessary.

@equalsraf, do you think it would be possible to [get rid of the *VCRUNTIME140.dll* dependency](https://stackoverflow.com/questions/35805113/visual-studio-2015-run-time-dependencies-or-how-to-get-rid-of-universal-crt ) and update the instructions on the [wiki page](https://github.com/neovim/neovim/wiki/Installing-Neovim#windows accordingly )?

**Comment by equalsraf** [comment] 2016-08-02 07:52
> @equalsraf, do you think it would be possible to get rid of the VCRUNTIME140.dll dependency and update the instructions on the wiki page?

@dumblob  in my experience linking against the static runtime results in other issues. In Neovim we tried doing this, but it prevented us from using other DLLs that link against VCRUNTIME140.dll (pre-built third-party dependencies, libuv, iconv, etc) and complicated out builds.a lot, so I ended up dropping it.

In practice its unlikely we can remove the dependency on the runtime DLL, remember Neovim also has other dependencies e.g. diff, clipboard tools, etc.

AFAIK the the best workaround I know of is the same used by regular windows installers, which is to include the c++ runtime redistributables installer as part of the installer for you application. But I have yet to find a good way how to do this with CMake/CPack.

**Comment by rgoliveira** [comment] 2016-08-02 07:58
> But I have yet to find a good way how to do this with CMake/CPack.
@equalsraf, is there and open issue about this? I'd like to get involved in neovim, and this seems like an okay-ish place.

**Comment by dumblob** [comment] 2016-08-02 08:05
@equalsraf apologies for the fuss. I wasn't aware of the attempts to make it so. I fully agree with including the redistributables into the installer.

**Comment by equalsraf** [comment] 2016-08-02 09:08
> @equalsraf apologies for the fuss. I wasn't aware of the attempts to make it so. I fully agree with including the redistributables into the installer.

No problem

> @equalsraf, is there an open issue about this? I'd like to get involved in neovim, and this seems like an okay-ish place.

No open issue, but it would be useful for both Neovim and Neovim-qt. Its mostly a matter of fiddling with CMake to get the c++ redistributables installer, bundle it with the installer (NSIS?) and call it as part of the instalation (maybe some custom NSIS logic for CPack?).

Here is [oldish post](http://voidknot.blogspot.pt/2013/12/shipping-visual-studio-redistributable.html) about doing it with NSIS. I don't think it covers multiple architectures though.

**Comment by equalsraf** [comment] 2016-08-02 10:12
@BohrShaw the win32yank in Neovim builds should be fixed now https://ci.appveyor.com/project/equalsraf/neovim/build/991/job/np6523vpr0gnf47d

**Comment by justinmk** [comment] 2016-08-02 13:37
Fwiw MS strongly discourages redistribution the CRT these days.

**Comment by equalsraf** [comment] 2016-08-02 13:40
> Fwiw MS strongly discourages redistribution the CRT these days.

True, and windows update (at least in Windows 10) should install this anyway, the problem is win 7 and 8.

**Comment by FigmentEngine** [comment] 2017-01-11 14:18
I've just installed on Windows 10 the latest version from
* https://github.com/neovim/neovim/wiki/Installing-Neovim
* https://github.com/equalsraf/neovim-qt/releases + win32yank.zip

but copy/paste to system clipboard not working - what do I have to do to configure use of win32yank.zip
:echo has('clipboard')
0

**Comment by justinmk** [comment] 2017-01-11 14:20
@FigmentEngine Still merging Windows-related PRs to Neovim master; it might be missing something from https://github.com/neovim/neovim/pull/810

**Comment by FigmentEngine** [comment] 2017-01-11 14:37
hmm seems help does not work either, as refenced by https://github.com/equalsraf/neovim-qt/issues/77
with version v0.2.0-365 on 64 bit windows 10

**Comment by justinmk** [comment] 2017-01-11 14:58
What is your folder layout? Where is nvim.exe in relation to share/?

**Comment by FigmentEngine** [comment] 2017-01-17 11:34
its in "C:\Program Files\nvim\Neovim\bin"
*doh*
moved it to "C:\Program Files (x86)\nvim\Neovim\bin" and everything works
sorry literally a newbie mistake.
thanks for your help!

**Comment by equalsraf** [comment] 2017-03-06 12:41
Closing, its fixed upstream.

**Closed by equalsraf** 2017-03-06 12:41 UTC
Labels: windows
