### ISSUE TITLE
Multiple cursors displayed when used with neovim master

### ISSUE THREAD

**Issue by svermeulen** [equalsraf/neovim-qt#541] opened 2019-05-18 20:02 UTC
Neovim version:
```
NVIM v0.4.0-770-ga3e0f05de
Build type: Debug
LuaJIT 2.0.5
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/Users/svermeulen/Projects/Ave/neovim/build/config -I/Users/svermeulen/Projects/Ave/neovim/src -I/Users/svermeulen/Projects/Ave/neovim/.deps/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/usr/include -I/Users/svermeulen/Projects/Ave/neovim/build/src/nvim/auto -I/Users/svermeulen/Projects/Ave/neovim/build/include
```

This issue only occurs with neovim-qt.  If I run terminal neovim and then create a terminal buffer it does not occur.

Repro steps:
- Execute `nvim-qt -- -u NORC`
- Enter terminal with `:terminal`
- Start typing and notice two cursors.  It seems as if one cursor is always one movement behind the other.  If I add whitespace by pressing space, the first cursor remains at the last letter.   If I add another letter, then it is always one character behind

![image](https://user-images.githubusercontent.com/810762/57974456-32ab6400-796d-11e9-88bf-9f3dd6e04d28.png)

![image](https://user-images.githubusercontent.com/810762/57974458-3c34cc00-796d-11e9-97f2-9570cafa9697.png)

**Comment by bfredl** [comment] 2019-05-18 21:04
Does https://github.com/neovim/neovim/pull/9882 (rebased on master) help?

**Comment by svermeulen** [comment] 2019-05-18 21:39
Nope.  If I build from that branch there's no bug.  But if I rebase that branch on to neovim master then I still get multiple cursors

**Comment by Kraust** [comment] 2019-05-23 01:46
Still seeing this with the latest neovim commit. Only seems to show up when you are in terminal mode. Before this bug manifested, I would see a second ghost cursor either in the top right, or seemingly random parts of the terminal buffer but only when in terminal mode.

**Comment by equalsraf** [comment] 2019-06-08 09:10
Sounds like a duplicate of https://github.com/equalsraf/neovim-qt/issues/291. Seems like we really need a workaround for :terminal mode.

**Comment by jgehrig** [comment] 2020-08-06 04:30
This issue no longer reproduces as of the latest release `v0.2.16`.

Marking as closed.

**Closed by jgehrig** 2020-08-06 04:30 UTC

**Comment by jgehrig** [comment] 2020-08-06 04:34
Related bugs: #640 #663
