### ISSUE TITLE
Can't get `Gui` commands to work / `NVIM_QT_RUNTIME_PATH` is not added to `runtimepath`

### ISSUE THREAD

**Issue by aleksey-rowan** [equalsraf/neovim-qt#1046] opened 2023-02-06 19:35 UTC
I'm sure I'm doing something obviously wrong, but I can't get `Gui` commands to work either on Windows 10 or Ubuntu/wsl. I've read through similar issues in this repo, but couldn't find anything could help me.

### On Windows

I add `NVIM_QT_RUNTIME_PATH` to variables and I can see that the variable is there, but it's not added to `runtimepath`:

```
> :echo $NVIM_QT_RUNTIME_PATH
c:\tools\neovim\nvim-win64\share\nvim-qt\runtime\

> :se runtimepath?
runtimepath=
~\.config\nvim,
~\AppData\Loca1\nvim-data\1azy\1azy.nvim,
~/AppData/Local/nvim~data/1azy/mkdir.nvim,
~\AppData\Loca1\nvim-data\1azy\true-zen.nvim,
~\AppData\Local\nvim-data\lazy\vim-colors-pencil,
~\AppData\Loca1\nvim-data\1azy\telekasten.nvim,
~\AppData\Loca1\nvim-data\1azy\te1escope-fzf-native.nvim,
~\AppData\Loca1\nvim-data\1azy\no-neck-pain.nvim,
~\AppData\Loca1\nvim-data\lazy\te1escope-heading.nvim,
~\AppData\Local\nvim-data\lazy\neovim-gui-shim,
~\AppData\Loca1\nvim-data\1azy\nvim-web-devicons,
~\AppData\Loca1\nvim-data\1azy\1ualine.nvim,
~\AppData\Loca1\nvim-data\1azy\nvim~treesitter,
~\AppData\Loca1\nvim-data\1azy\zen-mode.nvim,
~\AppData\Local\nvim-data\lazy\rasmus.nvim,
~\AppData\Loca1\nvim-data\1azy\leap.nvim,
~\AppData\Local\nvim-data\lazy\nvim-deardiary,
~\AppData\Loca1\nvim-data\1azy\nord-vim,
~\AppData\Loca1\nvim-data\1azy\gruvbox-baby,
~\AppData\Loca1\nvim-data\1azy\vim-unimpaixed,
~\AppData\Local\nvim-data\lazy\mkdnflow.nvim,
~\AppData\Loca1\nvim-data\1azy\yfix,
~\AppData\Loca1\nvim-data\1azy\plenary.nvim,
~\AppData\Loca1\nvim~data\1azy\te1escope.nvim,
~\AppData\Loca1\nvim-data\1azy\better-escape.nvim,
C:\tools\neovim\nvim-win64\share\nvim\runtime,
C:\tools\neovim\nvim-win64\share\nvim\runtime\pack\dist\opt\matchit,
C:\tools\neovim\nvim-win64\lib\nvim,
~\AppData\Loca1\nvim~data\1azy\readme,
~\AppData\Loca1\nvim-data\1azy\gruvbox-baby\after
```

Here's the output of `nvim-qt --version`:
![image](https://user-images.githubusercontent.com/79934725/217062667-67f7647f-a8b9-4e43-864b-4e4334a4aa8d.png)

I installed nvim with Chocolatey.

### On Ubuntu/wsl

I set `NVIM_QT_RUNTIME_PATH`, but again it's not on the `runtimepath`:

```
> echo $NVIM_QT_RUNTIME_PATH
/home/linuxbrew/.linuxbrew/Cellar/neovim-qt/0.2.17/bin/../share/nvim-qt/runtime

> :se runtimepath
runtimepath=
~/.config/nvim,
~/.local/share/nvim/lazy/lazy.nvim,
~/.local/share/nvim/lazy/vim-color-pencil,~/.local/share/nvim/lazy/mkdnflow.nvim,
~/.local/share/nvim/lazy/rasmus.nvim,
~/.1oca1/shara/nvim/lazy/plenary.nvim,~/.local/share/nvim/lazy/telescope.nvim,
~/.local/share/nvim/lazy/nvim-deardiary,~/.local/shere/nvim/lazy/true-zen.nvim,
~/.local/share/nvim/Iazy/nvim-treesitter,
~/.local/share/nvim/lazy/no-neck-pain.nvim,
~/.local/shere/nvim/lazy/gruvbox-baby,
~/.local/shere/nvim/lazy/leap.nvim,~/.local/shere/nvim/lazy/nord-vim,
~/.local/share/nvim/lazy/telescope-fzf-native.nvim,
~/.local/share/nvim/lazy/vim-unimpaired,
~/.local/shere/nvim/lazy/nvim-web-devicons,
~/.locaI/share/nvim/lazy/lualine.nvim,
~/.local/share/nvim/lazy/zen-mode.nvim,
~/.local/share/nvim/lazy/mkdir.nvim,
~/.local/share/nvim/lazy/better-escape.nvim,
~/.local/share/nvim/lazy/telescope-heading.nvim,
~/.locaI/share/nvim/lazy/yfix,~/.local/share/nvim/lazy/telekasten.nvim,
/home/1inuxbrew/.linuxbrew/Cellar/neovin/O.8.3/share/nvim/runtime,
/home/linuxbrew/.linuxbrew/Cellar/neovim/O.8.3/share/nvim/runtime/pack/1ist/opt/matchit,
/home/1inuxbrew/.linuxbrew/Cellar/neovim/O.8.3/1ib/nvim,
~/.local/state/nvim/lazy/readme,
~/.local/share/nvim/lazy/gruvbox-baby/after
```

Here's the output of `nvim-qt --version`:
```
NVIM—QT v0.2.17.0
Build type: Release
Compilation: -Wall -Wextra -Wno-unused-parameter —Wunused—variable —std=c++11
Qt Version: 5.15.5
Environment:

nvim: nvim

args: -cmd let &rtp.=',/home/linuxbrew/.linuxbrew/Cellar/neovim-qt/G.2.17/bin/../share/nvim-qt/runtime' -cmd set termgui
colors

runtime: /home/linuxbrew/.linuxbrew/Cellar/neovim-qt/G.2.17/bin/../share/nvim-qt/runtime
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by linuxbrew@leb16d0118e5
Features: +acl +iconv +tui
See ":help Feature-compile"

system vimrc File: "$VIM/sysinit.vim"

Fall-back For $VIM: "
/home/linuxbrew/.linuxbrew/Cellar/neovim/O.8.3/share/nvim"
Run :checkhealth For more info
```

I installed nvim and nvim-qt with homebrew. 

Thank you!

**Comment by jgehrig** [comment] 2023-02-17 01:15
Marking as closed -- this is a local configuration issue. However, let's still work to get your issue solved!

You should not need to set `NVIM_QT_RUNTIME_PATH`, unless the runtime/plugin files are placed in an unusual location.

**Question 1** On Linux/WSL, are [these files](https://github.com/equalsraf/neovim-qt/tree/master/src/gui/runtime) present at `/home/linuxbrew/.linuxbrew/Cellar/neovim-qt/G.2.17/bin/../share/nvim-qt/runtime`? On Windows, are the same files present at the `runtime:` location?

**Question 2** Do you see `nvim_gui_shim.vim` listed in the Vim command output, `:scriptnames`?

If you get desperate, you can always load this plugin into your plugin manager:
https://github.com/equalsraf/neovim-gui-shim

**Closed by jgehrig** 2023-02-17 01:15 UTC

**Comment by aleksey-rowan** [comment] 2023-02-17 02:09
Thank you for replying!

I'm not sure what is considered a usual location, but `:Gui` commands never worked and that's why I was trying to set `NVIM_QT_RUNTIME_PATH`.

> **Question 1:**
On Linux/WSL, are [these files](https://github.com/equalsraf/neovim-qt/tree/master/src/gui/runtime) present at /home/linuxbrew/.linuxbrew/Cellar/neovim-qt/G.2.17/bin/../share/nvim-qt/runtime? On Windows, are the same files present at the runtime: location?

Yes, these files are present, although on Windows `nvim_gui_shim.txt` is missing.

```
// WSL
ar@tf:/home/linuxbrew/.linuxbrew/Cellar/neovim-qt/0.2.17/share/nvim-qt/runtime$ ls */*
doc/nvim_gui_shim.txt  
doc/tags  
plugin/nvim_gui_shim.vim
```
```
// Windows
ar@tf MINGW64 /c/tools/neovim/nvim-win64/share/nvim-qt/runtime
$ ls */*
plugin/nvim_gui_shim.vim
```


> **Question 2:**
Do you see `nvim_gui_shim.vim` listed in the Vim command output, :scriptnames?

No, it's not there. There are no entries from `nvim-qt/runtime` at all on Windows and WSL.


> If you get desperate, you can always load this via your plugin manager:
https://github.com/equalsraf/neovim-gui-shim

I tried it and it works, but `equalsraf/neovim-gui-shim` [hasn't been updated in a while](https://github.com/equalsraf/neovim-gui-shim/issues/8) and is missing the most recent commands like "frameless".

**Comment by jgehrig** [comment] 2023-02-17 03:26
What happens when you run `nvim-qt -- -u NONE`?

Do the Gui commands work when no user configuration is present?

If not, is `nvim_gui_shim.vim` reported in `:scriptnames` for this case?

> I'm not sure what is considered a usual location, but :Gui commands never worked and that's why I was trying to set NVIM_QT_RUNTIME_PATH.

This is used for runtimes located outside of the default install path. On Windows, with the binary. On Linux/MacOS, /usr/share/nvim-qt/runtime.

In your case, you shouldn't need to use it.

Here is an example from my Development environment on Linux:
`NVIM_QT_RUNTIME_PATH=~/Development/neovim-qt/src/gui/runtime ./nvim-qt --nofork`


> Yes, these files are present, although on Windows nvim_gui_shim.txt is missing.

Try manually copying any missing files.

> No, it's not there. There are no entries from nvim-qt/runtime at all on Windows and WSL.

This is a problem.

The plugin is usually loaded with the command  `let &rtp.=',/usr/bin/../share/nvim-qt/runtime'`  on startup.

You can try running that command manually, to see if the script is loaded correctly. That might help is isolate the issue.

**Comment by jgehrig** [comment] 2023-02-17 03:27
> I tried it and it works, but equalsraf/neovim-gui-shim https://github.com/equalsraf/neovim-gui-shim/issues/8 and is missing the most recent commands like "frameless".

Yes, we should update this. Thanks for filing the bug!

I'll add it to my list of things TODO :)

**Comment by aleksey-rowan** [comment] 2023-02-17 03:40
> What happens when you run `nvim-qt -- -u NONE`?
> 
> Do the Gui commands work when no user configuration is present?

Yes, `Gui` commands are present with `nvim-qt -- -u NONE`.

**Comment by aleksey-rowan** [comment] 2023-02-19 03:17
Forgot to mention: `Gui` commands are present in both WLS and Windows with `-u NONE`. 

Does it mean that something in my `init.lua` prevents `neovim-gui-shim` from loading? Is there an easy way to find out apart from disabling things one by one?

**Comment by jgehrig** [comment] 2023-02-22 02:56
> Does it mean that something in my init.lua prevents neovim-gui-shim from loading? Is there an easy way to find out apart from disabling things one by one?

Yes -- It looks like something in your `init.lua`, `init.vim`, or `ginit.vim` files is causing issues.

You can try commenting out blocks of the file to isolate where the issue is.

I would also look at your plugin manager, or any modifications to `rtp`.

**Comment by Sh00Fly** [comment] 2023-10-23 20:38
I ran into the same/similar problem. Here is what resolved it for me. Maybe it will be useful for somebody.

```lua

-- I made local variables for lists of plugins, and options for lazy.nvim
-- Then I call a setup function and pass these lists into it.
-------------------------------------------------------------------------
local plugins = {
    {'tpope/vim-fugitive'},
    -- ...
    {'folke/which-key.nvim', opts = {}},
}
-------------------------------------------------------------------------
local opts = {
    performance = {
        rtp = {
            -- This option is what fixed the problem for me.
            -- Apparently, Lazy.nvim removes NeovimQT's runtime path from rtp.
            -- Then what happens is that NeovimQT can't find it's nvim_gui_shim.vim.
            -- And then GUI... commands don't work.
            paths = {'C:\\Program Files\\Neovim\\share\\nvim-qt\\runtime\\'} -- add any custom paths here that you want to includes in the rtp
        }}}
-------------------------------------------------------------------------
-- Here I call Lazy.nvim and pass the two lists above into the setup function.
require('lazy').setup(plugins, opts)
```

**Comment by surmish** [comment] 2024-01-03 00:25
> I ran into the same/similar problem. Here is what resolved it for me. Maybe it will be useful for somebody.
> 
> ```lua
> -- I made local variables for lists of plugins, and options for lazy.nvim
> -- Then I call a setup function and pass these lists into it.
> -------------------------------------------------------------------------
> local plugins = {
>     {'tpope/vim-fugitive'},
>     -- ...
>     {'folke/which-key.nvim', opts = {}},
> }
> -------------------------------------------------------------------------
> local opts = {
>     performance = {
>         rtp = {
>             -- This option is what fixed the problem for me.
>             -- Apparently, Lazy.nvim removes NeovimQT's runtime path from rtp.
>             -- Then what happens is that NeovimQT can't find it's nvim_gui_shim.vim.
>             -- And then GUI... commands don't work.
>             paths = {'C:\\Program Files\\Neovim\\share\\nvim-qt\\runtime\\'} -- add any custom paths here that you want to includes in the rtp
>         }}}
> -------------------------------------------------------------------------
> -- Here I call Lazy.nvim and pass the two lists above into the setup function.
> require('lazy').setup(plugins, opts)
> ```

Thanks, this helped!

**Comment by boytom** [comment] 2024-10-03 09:20
> > I ran into the same/similar problem. Here is what resolved it for me. Maybe it will be useful for somebody.
> > ```lua
> > -- I made local variables for lists of plugins, and options for lazy.nvim
> > -- Then I call a setup function and pass these lists into it.
> > -------------------------------------------------------------------------
> > local plugins = {
> >     {'tpope/vim-fugitive'},
> >     -- ...
> >     {'folke/which-key.nvim', opts = {}},
> > }
> > -------------------------------------------------------------------------
> > local opts = {
> >     performance = {
> >         rtp = {
> >             -- This option is what fixed the problem for me.
> >             -- Apparently, Lazy.nvim removes NeovimQT's runtime path from rtp.
> >             -- Then what happens is that NeovimQT can't find it's nvim_gui_shim.vim.
> >             -- And then GUI... commands don't work.
> >             paths = {'C:\\Program Files\\Neovim\\share\\nvim-qt\\runtime\\'} -- add any custom paths here that you want to includes in the rtp
> >         }}}
> > -------------------------------------------------------------------------
> > -- Here I call Lazy.nvim and pass the two lists above into the setup function.
> > require('lazy').setup(plugins, opts)
> > ```
> 
> Thanks, this helped!

So sorry and I am new to neovim and neovim-qt。Can anyone tell me which file to modify?

**Comment by Sh00Fly** [comment] 2024-10-04 03:42
> > > I ran into the same/similar problem. Here is what resolved it for me. Maybe it will be useful for somebody.
> > > ```lua
> > > -- I made local variables for lists of plugins, and options for lazy.nvim
> > > -- Then I call a setup function and pass these lists into it.
> > > -------------------------------------------------------------------------
> > > local plugins = {
> > >     {'tpope/vim-fugitive'},
> > >     -- ...
> > >     {'folke/which-key.nvim', opts = {}},
> > > }
> > > -------------------------------------------------------------------------
> > > local opts = {
> > >     performance = {
> > >         rtp = {
> > >             -- This option is what fixed the problem for me.
> > >             -- Apparently, Lazy.nvim removes NeovimQT's runtime path from rtp.
> > >             -- Then what happens is that NeovimQT can't find it's nvim_gui_shim.vim.
> > >             -- And then GUI... commands don't work.
> > >             paths = {'C:\\Program Files\\Neovim\\share\\nvim-qt\\runtime\\'} -- add any custom paths here that you want to includes in the rtp
> > >         }}}
> > > -------------------------------------------------------------------------
> > > -- Here I call Lazy.nvim and pass the two lists above into the setup function.
> > > require('lazy').setup(plugins, opts)
> > > ```
> > 
> > 
> > Thanks, this helped!
> 
> So sorry and I am new to neovim and neovim-qt。Can anyone tell me which file to modify?

Oh, I wouldn't know which file it is your particular configuration, but it's the one where you call Lazy to install/load all the plugins.
It's where you have the line:
```lua
require("lazy").setup(plugins, opts)
```

**Comment by boytom** [comment] 2024-10-04 07:48
> > > > I ran into the same/similar problem. Here is what resolved it for me. Maybe it will be useful for somebody.
> > > > ```lua
> > > > -- I made local variables for lists of plugins, and options for lazy.nvim
> > > > -- Then I call a setup function and pass these lists into it.
> > > > -------------------------------------------------------------------------
> > > > local plugins = {
> > > >     {'tpope/vim-fugitive'},
> > > >     -- ...
> > > >     {'folke/which-key.nvim', opts = {}},
> > > > }
> > > > -------------------------------------------------------------------------
> > > > local opts = {
> > > >     performance = {
> > > >         rtp = {
> > > >             -- This option is what fixed the problem for me.
> > > >             -- Apparently, Lazy.nvim removes NeovimQT's runtime path from rtp.
> > > >             -- Then what happens is that NeovimQT can't find it's nvim_gui_shim.vim.
> > > >             -- And then GUI... commands don't work.
> > > >             paths = {'C:\\Program Files\\Neovim\\share\\nvim-qt\\runtime\\'} -- add any custom paths here that you want to includes in the rtp
> > > >         }}}
> > > > -------------------------------------------------------------------------
> > > > -- Here I call Lazy.nvim and pass the two lists above into the setup function.
> > > > require('lazy').setup(plugins, opts)
> > > > ```
> > > 
> > > 
> > > Thanks, this helped!
> > 
> > 
> > So sorry and I am new to neovim and neovim-qt。Can anyone tell me which file to modify?
> 
> Oh, I wouldn't know which file it is in your particular configuration, but it's the one where you call Lazy to install/load all the plugins. It's where you have the line:
> 
> ```lua
> require("lazy").setup(plugins, opts)
> ```

Think you! I get it. I am using a Windows machine, and the file used to load Lazy plugins is 
```
%LOCALAPPDATA%\nvim\lua\config\lazy.lua
```

The patch of lazy.lua is:

```
--- lazy.lua	2024-10-04 15:47:16.110174200 +0800
+++ lazy_new.lua	2024-10-04 15:47:01.393453800 +0800
@@ -42,6 +42,7 @@
         "tutor",
         "zipPlugin",
       },
+      paths = {"E:\\DevelopTools\\nvim\\neovim-qt\\share\\nvim-qt\\runtime\\"},
     },
   },
 })
```

May be this will help someone.
