### ISSUE TITLE
Error: Neovim is taking too long to respond

### ISSUE THREAD

**Issue by dav2017** [equalsraf/neovim-qt#360] opened 2017-11-17 11:02 UTC
Hi,

Running "nvim-qt filename" I get (for some files) the following error:
  Neovim fatal error "Neovim is taking too long to respond"
The error is specific for nvim-qt, as I can open the file using nvim.
Also, if I first start nvim-qt and then open the file. e.g. with :e filename
there is no problem with the file.

It never happened before updating to the last nvim-qt last week (from git-hub. Also, I tried to pull and recompile again this morning, but the problem is still here).
No other message is print out, the only thing is that the file where first edited with gvim (but some of them also re-edited by nvim-qt).

neovim version: 0.2.1 (but tired also with 0.2.0)
OS: Debian GNU/Linux

Thanks for help,

   Davide

**Comment by equalsraf** [comment] 2017-11-20 10:45
Sounds like a duplicate of https://github.com/equalsraf/neovim-qt/issues/78 what happens when you run the same command with nvim? If you are getting any kind of error when opening that file (the typical case would be a swap file error message).

**Comment by dav2017** [comment] 2017-11-20 11:28
I did not realize it at first, but the problem is indeed due to the presence of a swap file.
While nvim warns that a swap file already exists,  in ~/.local/share/nvim/swap, and asks what to do, nvim-qt is stuck (probably waiting for nvim, which is waiting for an input to chose how to proceed).
Thanks for the replay. If the problem is the same of [#78](https://github.com/equalsraf/neovim-qt/issues/78) it seems I just have to wait for a future fix.
Thanks

**Comment by equalsraf** [comment] 2017-11-20 11:50
Ok, closing this then.

**Closed by equalsraf** 2017-11-20 11:50 UTC

**Comment by jon49** [comment] 2017-12-14 15:58
For others that come across this with a web search. Use the command:

```
"C:\Program Files\Neovim\bin\nvim.exe"  -u NONE -V
```

To find out what was hanging it up. For me it was 

> Reading ShaDa file "C:\Users\jon.nyman\AppData\Local\nvim-data\shada\main.shada" info marks oldfiles
> E576: Error while reading ShaDa file: there is an item at position 8991 that must not be there: Missing items are for internal uses only

So, I just deleted everything in that directory. Now it works fine.
