### ISSUE TITLE
Background color of changed lines in vimdiff mode using "apprentice" and other colorscheme does not change in nvim-qt

### ISSUE THREAD

**Issue by shlomif** [equalsraf/neovim-qt#687] opened 2020-05-04 09:45 UTC
See https://github.com/shlomif/neovim-qt-bgcolor-apprentice-colorscheme-bug :

The background color of changed lines in nvim-qt using the apprentice colorscheme,
and in vimdiff is not the same as nvim, vim or gvim. nvim/nvim-qt from git master.

```
Linux localhost.localdomain 5.6.8-300.fc32.x86_64 #1 SMP Wed Apr 29 19:01:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

To reproduce run `bash run-nvim-qt.bash`.

**Comment by jgehrig** [comment] 2020-05-05 05:35
@shlomif Thanks for the bug report!

That color scheme uses the following highlight:
`  hi DiffChange       ctermbg=235  ctermfg=103  guibg=#262626 guifg=#8787af cterm=reverse        gui=reverse`

This looks like a duplicate of Issue #674. There is also an outstanding Pull Request #675.

The patch above should resolve your issues:
![image](https://user-images.githubusercontent.com/11207308/81037344-59112a80-8e70-11ea-959b-47a395bff9b0.png)

**Comment by shlomif** [comment] 2020-05-05 05:49
@jgehrig : thanks for the comment and insight. I'm going to try the patch here.

**Comment by shlomif** [comment] 2020-05-05 06:07
@jgehrig : the patch appears to have fixed the problem here - thanks!

**Closed** 2020-06-15 03:29 UTC
