### ISSUE TITLE
US English International keyboard with dead keys does not work properly in Windows

### ISSUE THREAD

**Issue by kayzzen01** [equalsraf/neovim-qt#992] opened 2022-06-12 21:13 UTC
Hi,

On the US English international keyboard with dead keys the symbols/accents are displayed only when you press the space (at least in Windows and Linux this is usually the case).
If I want to type ~ I will need to type ~ + space.

In VIM I tried just now and it worked, but if I type the same keys in NeoVIM, a space appears. In order for me to get the ~ character in NeoVIM it is necessary to type ~ twice and the editor writes the ~ character twice.

Tests:
```
VIM/gVIM : ~ + space = ~
NeoVIM   : ~ + space = ~
NeoVIM-QT: ~ + space = space
NeoVIM-QT: ~~ = ~~
```

This issue only occurs in the GUI(qt) version of NeoVIM.

Operating System: Windows 10 64 bit 21H2
NeoVIM QT v0.7.0 64 bit

**Comment by jgehrig** [comment] 2022-07-10 13:09
This looks like a duplicate of #270.

Can you try again with the latest release of neovim-qt, found [here](https://github.com/equalsraf/neovim-qt/releases/tag/v0.2.17).

**Comment by kayzzen01** [comment] 2022-07-16 19:14
Hi @jgehrig,

I'm sorry! The last few weeks have been very difficult for me. I should have answered you sooner.

NeoVIM-QT in the version you suggested continues with the same problems that I reported.

I'll repost the description of this issue in the previous issue(#270), but from what I've seen there is no plan to solve this problem.

Thanks

**Comment by jgehrig** [comment] 2022-07-17 01:35
> I'm sorry! The last few weeks have been very difficult for me. I should have answered you sooner.

No worries! Been there, I get it... I hope things have calmed down or will soon.

Re-opening the issue, I will take a look in more detail when I get a chance.

I need to be able to reproduce the issue locally, or you need to generate the key events here:
https://github.com/equalsraf/neovim-qt/blob/7b230767dd04d921ca5c2c31ad46ffd00111aed2/src/gui/shell.cpp#L1367-L1369

> I'll repost the description of this issue in the previous issue(https://github.com/equalsraf/neovim-qt/issues/270), but from what I've seen there is no plan to solve this problem.

No, I am certainly willing to fix this issue or any other input issues!  :)

The original issue in 270 was fixed. Generally, it is best to not revive old large threads like that (not a problem though).

Let's continue the discussion of your issues here.

**Closed** 2022-10-01 13:27 UTC
