### ISSUE TITLE
Nvim recovery  does not work.

### ISSUE THREAD

**Issue by koppa** [equalsraf/neovim-qt#173] opened 2016-08-21 23:24 UTC
Nvim recovery mode leads to an error in nvim-qt.

## Reproduction:

   # open a new file
   nvim /tmp/testfile
   # now kill this process

   # open in nvim-qt
   nvim-qt /tmp/testfile

## Result:

![Nvim error](http://i.imgur.com/WOJ2M3D.png)

## Expected Behaviour:

A window with the recovery options

for example:

![recovery options](http://i.imgur.com/xGOsKVs.png)

**Comment by equalsraf** [comment] 2016-08-22 06:53
This is the duplicate of https://github.com/equalsraf/neovim-qt/issues/78, and will have to wait for some fixes upstream.

**Closed by equalsraf** 2016-08-22 06:53 UTC
