### ISSUE TITLE
Can't input the uppercase "c cedilha" (Ç)

### ISSUE THREAD

**Issue by noamcore** [equalsraf/neovim-qt#316] opened 2017-08-01 14:45 UTC
### Info
Software|Version
-----------------|--------------
Netrunner Rolling OS|2017.07
neovim-qt<sup>[AUR]</sup>|0.2.7-1

---

While using the neovim-qt, I needed to put the "Ç" but the app seems to don't recognize that letter.

Curiously I can put the normal ç.

**Comment by MMDF** [comment] 2017-08-21 11:05
Also happens here.

**Comment by jamessan** [comment] 2017-08-24 00:39
Sounds like a duplicate of #270.

**Comment by noamcore** [comment] 2017-08-24 19:29
I'm not using Windows, and the "Ç" is not a dead key. So I don't think that it is a duplicate.

**Comment by equalsraf** [comment] 2017-08-25 14:23
What keyboard layout are you using? 

```
$ setxkbmap  -print
```

What keys do you press to insert upper and lower case Ç?

I assume creating an imap for Ç does not work. Is any of these mappings triggered when you the key it?

```vim
    imap Ç test1
    imap <S-Ç> test2
```

To figure it out further we would need to debug what is being sent to nvim in this call https://github.com/equalsraf/neovim-qt/blob/master/src/gui/shell.cpp#L590

**Comment by noamcore** [comment] 2017-08-26 14:26
Keyboard layout is `br-abnt2`.

The key used is a common key. You can see from this (right side of L) ![](https://http2.mlstatic.com/teclado-asus-k43u-x430-x43u-padrao-br-abnt2-com-c-ab5-D_NQ_NP_917701-MLB20377522013_082015-F.jpg).

So

    lower case = ç
    upper case = Shift-ç

**Comment by noamcore** [comment] 2017-08-26 14:53
Sorry about that, but seems that the `yaourt` gets the bugged version when not using the neovim-qt-git.

Now that I've cloned and compiled, the GUI is working as expected.

Really sorry.

**Comment by equalsraf** [comment] 2017-08-26 15:07
No problem at all. Closing this then.

Quick check on AUR https://aur.archlinux.org/packages/?O=0&SeB=nd&K=neovim-qt&outdated=&SB=n&SO=a&PP=50&do_Search=Go shows that package is using v0.2.4.

**Closed by equalsraf** 2017-08-26 15:07 UTC
