### ISSUE TITLE
Allow separate font for icons

### ISSUE THREAD

**Issue by famiu** [equalsraf/neovim-qt#832] opened 2021-04-09 04:56 UTC
So today I realized the Kitty terminal allows using a separate font for devicons so it's not necessary to patch fonts for devicons. I was wondering if it'd be possible to implement such a functionality in Neovim-qt so we can have two fonts, one for the text and another to provide the devicons. And if it's not possible, is it because it requires extra functionality from Neovim or is it because of a limitation of Neovim-qt?

**Comment by jgehrig** [comment] 2021-04-09 11:13
Have you tried setting `guifontwide`?

That should allow you to set a list of fonts to use for double-cell characters (emoji, CJK, icons, etc).

**Comment by Famiu** [comment] 2021-04-09 11:34
I just tried and it doesn't seem to do anything different. For some reason, the glyphs appear when I use a non-patched font both with and without setting guifontwide, and both of the cases it's rendered incorrectly, screenshot:
![image](https://user-images.githubusercontent.com/29580810/114174031-dd5e0e80-9959-11eb-99df-61b7174be879.png)

**Comment by jgehrig** [comment] 2021-04-09 13:59
What did you try? Providing versions of any relevant packages and an explicit set of steps helps me reproduce your issue...

The option `:set guifontwide=` is relatively new. Although, if you're using `GuiRenderLigatures`, you probably have a new enough version.

Here is an example:
![guifontwide_example](https://user-images.githubusercontent.com/11207308/114190732-a1a35480-9919-11eb-9ab5-8d9482a0bddd.gif)

See `:help guifontwide` for details. The approach would only work for double-width characters/icons.

**Comment by Famiu** [comment] 2021-04-09 14:43
> What did you try? Providing versions of any relevant packages and an explicit set of steps helps me reproduce your issue...
> 
> The option `:set guifontwide=` is relatively new. Although, if you're using `GuiRenderLigatures`, you probably have a new enough version.
> 
> Here is an example:
> ![guifontwide_example](https://user-images.githubusercontent.com/11207308/114190732-a1a35480-9919-11eb-9ab5-8d9482a0bddd.gif)
> 
> See `:help guifontwide` for details. The approach would only work for double-width characters/icons.

I meant to say, I already tried the guifontwide issue. I'm using the latest nightly of Neovim as of today and the master branch of Neovim-qt. My ginit.vim is also in the screenshot I posted

**Comment by jgehrig** [comment] 2021-04-09 14:57
I still don't know what steps you're doing... Without more info, I can't help any further.

The `guifontwide` feature is generally the option to accomplish what you've asked.

It is theoretically possible to add a new option that overrides fonts for specific characters. That is essentially how `guifontwide` operates. However, it would be yet another configuration option to test and maintain. It would also be neovim-qt specific, something I would prefer to avoid.

I'd like to keep `neovim-qt` simple and as close to the Terminal UI as possible.

**Comment by Famiu** [comment] 2021-04-09 16:25
> I still don't know what steps you're doing... Without more info, I can't help any further.
>
What do you exactly mean here? If you mean what I did, I set the guifont and the guifontwide values to "Fira Code" and "Fira Code Nerd Font Mono" respectively to test it out. And it rendered the texts incorrectly as I showed in the screenshot above.
> The `guifontwide` feature is generally the option to accomplish what you've asked.
> 
But it doesn't seem to work as intended, as you can see in that screenshot.
> It is theoretically possible to add a new option that overrides fonts for specific characters. That is essentially how `guifontwide` operates. However, it would be yet another configuration option to test and maintain. It would also be neovim-qt specific, something I would prefer to avoid.
> 
> I'd like to keep `neovim-qt` simple and as close to the Terminal UI as possible.
That is totally understandable.

**Comment by jgehrig** [comment] 2021-04-09 16:45
Sorry, perhaps I'm being slow... But I don't see the rendering issue in your screenshot.

Usually, a very explicit set of steps is helpful to understand what you're doing.

It also helps to describe expected vs observed behavior.

Here is an example usage:
1) Start neovim with an empty config -- `nvim-qt -- -u NONE`
2) Paste "😀 😃 😄 😁 😆 😅 😂 🤣" into the buffer.
3) Type "Hello World" on the next line
4) Call `:set GuiFont! Hack:h11` to set the font
5) Call `:set guifontwide=Noto\ Sans\ Color\ Emoji:h11` to set the wide character font.
6) Notice the emoji-s change font but "Hello World" does not.

This option will only work for characters occupying two cells (emoji, CJK, symbols). It may not work for you case... I'm not clear on the exact rendering issue you're experiencing.

Regarding the feature request, I think this is a good idea. However, (IMO) it should be directed upstream to Neovim or even better Vim. Lots of users want the ability to render specific characters with a special font for plugins like `vim-airline`. If the option is valuable enough to include, it should be available for everyone: gVim, Neovim, Neovim Frontends.

**Comment by Famiu** [comment] 2021-04-09 17:00
> Sorry, perhaps I'm being slow... But I don't see the rendering issue in your screenshot.
>
It's in the statusline
> Usually, a very explicit set of steps is helpful to understand what you're doing.
> 
> It also helps to describe expected vs observed behavior.
> 
Ah, so that's what you mean. Alright then. Here's the steps:

1. Start neovim with an empty config -- `nvim-qt -- -u NONE`

2. Paste "😀😁😂🤣😃😄" into the buffer.

3. Type "Hello World" on the next line

4. Call `:set guifont=JetBrains\ Mono:h10` to set the font

5. Call `:set guifontwide=Noto\ Sans\ Color\ Emoji:h10` to set the wide character font.

6. Notice rendering issue. Screenshot:
![image](https://user-images.githubusercontent.com/29580810/114215189-1f517980-9987-11eb-9e87-15e22345fb40.png)



> This option will only work for characters occupying two cells (emoji, CJK, symbols). It may not work for you case... I'm not clear on the exact rendering issue you're experiencing.
> 
> Regarding the feature request, I think this is a good idea. However, (IMO) it should be directed upstream to Neovim or even better Vim. Lots of users want the ability to render specific characters with a special font for plugins like `vim-airline`. If the option is valuable enough to include, it should be available for everyone: gVim, Neovim, Neovim Frontends.
> 
So would you suggest I put it as an issue on Neovim or Vim? I'd probably prefer putting it on Neovim since that's what I mainly use so I may not be able to try the feature out unless it gets adapted to Neovim as well

**Comment by jgehrig** [comment] 2021-04-09 17:27
Okay, that doesn't look right!

This is a tricky feature. Vim/Neovim is cell based, each character occupies a cell on the grid. When you mix/match fonts clipping issues can occur. We set the cell size based on the `guifont`, not `guifontwide`.

It looks like there is font-size mismatch, but I find it odd that "Hello Wold" is clipped. Usually the wide characters (emoji) are clipped instead.

What platform are you running? Linux? I will try to investigate further with those specific fonts...

> So would you suggest I put it as an issue on Neovim or Vim? I'd probably prefer putting it on Neovim since that's what I mainly use so I may not be able to try the feature out unless it gets adapted to Neovim as well

I have a feeling you'll probably get push-back from either project... It can't hurt to make the request though.

Usually the Neovim team integrates fixes/features from Vim. Either should work.

**Comment by Famiu** [comment] 2021-04-09 17:46
> Okay, that doesn't look right!
> 
> This is a tricky feature. Vim/Neovim is cell based, each character occupies a cell on the grid. When you mix/match fonts clipping issues can occur. We set the cell size based on the `guifont`, not `guifontwide`.
> 
> It looks like there is font-size mismatch, but I find it odd that "Hello Wold" is clipped. Usually the wide characters (emoji) are clipped instead.
> 
> What platform are you running? Linux? I will try to investigate further with those specific fonts...
> 
I'm running Arch Linux.
> > So would you suggest I put it as an issue on Neovim or Vim? I'd probably prefer putting it on Neovim since that's what I mainly use so I may not be able to try the feature out unless it gets adapted to Neovim as well
> 
> I have a feeling you'll probably get push-back from either project... It can't hurt to make the request though.
> 
> Usually the Neovim team integrates fixes/features from Vim. Either should work.
> 
On second thought, is there really any chance of getting it accepted in Vim or Neovim because for (Neo)Vim themselves to support multiple fonts, the terminal has to support it, and there's probably no easy to know if it does, unless of course they make it a GUI-only thing.

**Comment by jgehrig** [comment] 2021-04-09 17:54
Both support some GUI-only features: `guifont`, `guicursor`, `guifontwide`

The idea being to provide a uniform configuration mechanism for frontends like gVim.

Although without implementing the feature yourself, I think the chances are slim...

**Comment by jgehrig** [comment] 2021-04-09 18:12
Hmmm I cannot reproduce your screenshot...

I got similar clipping behavior once when I accidentally ran `:set guifont=Noto\ Color\ Emoji:h10`.

One thing to try: temporarily disable ligatures with `:GuiRenderLigatures 0`.

Anyways, the `guifontwide` feature is only helpful if your "devicons" are double-cell characters... I'm still not sure if your icons are double-cell?

**Comment by equalsraf** [comment] 2021-04-09 18:36
> It looks like there is font-size mismatch, but I find it odd that "Hello Wold" is clipped. Usually the wide characters (emoji) are clipped instead.

Indeed, but the emoji font heigh does look smaller. Maybe the clipping happens at the widefont height.

I have tried here by forcing guifontwide to the same font i use in guifont but with different height, but i cannot reproduce this issue:

- nvim-qt from master branch
- linux
- nvim-qt -- -u NORC

On my system the noto font does issue a warning

```
"Noto Color Emoji" Average and Maximum font width mismatch for Regular font; QFont::exactMatch() is true Real font is  "Noto Color Emoji" 11
```

Once I turned GuiRenderLigatures on, then I did start seeing some issues when using  guifont=Noto, even without the guifontwide. The white space in `hello world` disappeared, and in some conditions text was invisible. But nothing like was is displayed above.

**Comment by Famiu** [comment] 2021-04-09 18:50
> Hmmm I cannot reproduce your screenshot...
> 
> I got similar clipping behavior once when I accidentally ran `:set guifont=Noto\ Color\ Emoji:h10`.
> 
> One thing to try: temporarily disable ligatures with `:GuiRenderLigatures 0`.
> 
> Anyways, the `guifontwide` feature is only helpful if your "devicons" are double-cell characters... I'm still not sure if your icons are double-cell?

Strangely enough, it works better with ligatures turned off, not perfect because it still doesn't go perfectly with the normal gui font, but I assume it's because of the fonts themselves and not because of an issue with Neovim-qt. Somehow this time the text wasn't clipped even with ligatures on though, they emojis were just much higher up than usual

**Comment by jgehrig** [comment] 2021-04-09 19:34
> Strangely enough, it works better with ligatures turned off

Haha not strange at all! :sweat_smile:

Ligatures are new and still quite buggy. The Qt API for ligatures is difficult to work with. It *almost* makes me wish I had never implemented the feature...

The size mismatch is a result of using two fonts where each has a different size. Unless the two fonts are exactly the same size, you will get clipping or offset. Usually, I just tweak the size of `guifontwide` until it looks reasonable.

Perhaps the cell size can be set more intelligently set to avoid this issue? I will think about this...

**Comment by equalsraf** [comment] 2021-04-09 20:13
> Ligatures are new and still quite buggy. The Qt API for ligatures is difficult to work with. It almost makes me wish I had never implemented the feature...

This made me laugh, font rendering really is one of the 3 sources of evil in software.

Not much i can offer here, other than a drink, a pat in the back and high praise (or the equivalent linkedin recommendation).

It might be worth testing with a couple of fonts here, we might be just tripping on a really weird font.

**Comment by Famiu** [comment] 2021-04-10 04:23
> It might be worth testing with a couple of fonts here, we might be just tripping on a really weird font.
> 
I tried with Fira Code, Source Code Pro and JetBrains Mono.

**Comment by swag-lab** [comment] 2021-04-13 03:38
+1
`:GuiRenderLigatures 0` does the trick. Icons weren't ok (they were cut off) while Ligatures are turned on.

**Comment by swag-lab** [comment] 2021-04-13 09:22
https://user-images.githubusercontent.com/79488680/114529310-74330f80-9c67-11eb-94dd-49855c1acba5.mp4

As you can see, the icons are cut off when ligatures are turned On.

**Comment by jgehrig** [comment] 2021-04-20 17:42
Closing this issue. The `guifontwide` feature allows for this behavior.

Acknowledged, we have `:GuiRenderLigatures` issues. We will track ligature-specific problems in Issue #771.

Please let me know if I'm missing something.

**Closed by jgehrig** 2021-04-20 17:42 UTC

**Comment by jgehrig** [comment] 2021-04-20 18:20
> This made me laugh, font rendering really is one of the 3 sources of evil in software.
> Not much i can offer here, other than a drink, a pat in the back and high praise (or the equivalent linkedin recommendation).
> It might be worth testing with a couple of fonts here, we might be just tripping on a really weird font.

Hahaha

While the bugs are discouraging... It is also a sign the feature is valued and being used!

Duly noted on LinkedIn and the back pat. If you ever find yourself in Boston, I'd definitely take that drink! :beers:
