### ISSUE TITLE
Alt Gr does not work

### ISSUE THREAD

**Issue by Hofsmo** [equalsraf/neovim-qt#510] opened 2019-01-21 14:02 UTC
Hi,
When I push the Alt Gr button neovim-qt does not seem to recognize it. Neovim on the other hand recognizes it. I need Alt Gr for ~, $ and other characters since I have a Norwegian keyboard. Does anyone have a fix for this?

**Comment by Hofsmo** [comment] 2019-01-21 16:44
Hi, thanks for the reply.

I normally use vim in the gnome terminal. However, at work I have to use windows, so since I anyway was trying something new I decided to give neovim a shot. 

For the terminal emulator I testsed neovim with cmd and I could use Alt Gr to write ~,$, etc.

I don't have access to my work computer right now, but I will check tomorrow exactly which version of windows it is running and I will install some other Qt editor to check if Alt Gr works there.

**Comment by Hofsmo** [comment] 2019-01-22 07:17
@gagbo your solution kind of works. It works for some letters which I write using AltGr+key. The normal way to write ~ is a bit more complicated as it is normally written using AltGr+key then followed by space. Now I can write ~ by typing Ctrl+v AltGr+key+(any letter) then I have to delete the letter I made instead of pushing space.

**Comment by gagbo** [comment] 2019-01-22 09:22
It was solely for debugging purposes. `^V` writes the raw input neovim got, so it's just something to help debug the issue :)

So when you do ^V and type `AltGr+tilde_key+<Space>` nothing happens ? You have to type another letter ? When you type another letter, do you have the ~ on the letter or do you have 2 glyphs like `~n` (if you go `^V AltGr+tilde_key+n` for example)

**Comment by ravicious** [comment] 2019-01-22 18:54
I tried the Ctrl+v trick and it doesn't work for me, maybe I misunderstood something but I press `Ctrl + v` in insert mode and then `Alt + o`, but instead of getting `ó` I just get nothing, the editor is stuck in displaying highlighted `^`, as if it was awaiting a key.

**Comment by Hofsmo** [comment] 2019-01-23 07:32
> 
> 
> I tried the Ctrl+v trick and it doesn't work for me, maybe I misunderstood something but I press `Ctrl + v` in insert mode and then `Alt + o`, but instead of getting `ó` I just get nothing, the editor is stuck in displaying highlighted `^`, as if it was awaiting a key.

Hi, I think the combination you wrote after `Ctrl + v` maybe doesn't do anything. At least if I do `Ctrl + v` and something that doesn't do anything I get the behavior you describe. Have you tried some other combinations?

**Comment by ravicious** [comment] 2019-04-06 10:43
Here's the issue I have on macOS with the `Ctrl + v` solution in insert mode: https://streamable.com/gmven

On the right I have VimR open (where diacritics work as expected), on the left I have neovim-qt.

I use Polish Pro keyboard, so `alt + e` is supposed to insert `ę`, `alt + o` is supposed to insert `ó` and so on.

**Comment by ningsuhen** [comment] 2019-06-14 08:48
+1.

I have my Option key mapped to Meta. Now my vimrc has mappings for <M-..>. All of these work in terminals and VimR, Unfortunately, it doesn't work in neovim-qt.

**Comment by ravicious** [comment] 2019-08-09 06:47
I still have problems with it on neovim-qt v0.2.13 compiled with qt 5.13.0. It's kinda irritating sometimes because not only I can't input diacritics from my native language, but I also can't write stuff like en dashes or ellipsis.

I noticed that Streamable removed my video for some reason, so I recorded a new one, this time uploaded to GitHub so it won't get removed. Again, on the left there's VimR where everything works as expected, on the right I have neovim-qt open.

[neovim-qt-alt-gr.mov.zip](https://github.com/equalsraf/neovim-qt/files/3485081/neovim-qt-alt-gr.mov.zip)

**Comment by jgehrig** [comment] 2019-12-27 01:15
@ravicious @Hofsmo @ningsuhen

Can anyone provide the corresponding QKeyEvents for your input?

If you provide this input, I can try to fix your scenario in #612 .

To fix an input sequence I need:
1. Raw QKeyEvent for your platform (see patch below).
2. A brief description of what you typed.
3. The input you expected from your key sequences.

Apply this patch to log QKeyEvents for every key press:
``` patch
diff -r a4b43d295f61 src/gui/shell.cpp
--- a/src/gui/shell.cpp Mon Dec 16 02:23:57 2019 -0500
+++ b/src/gui/shell.cpp Thu Dec 26 10:58:19 2019 -0500
@@ -1070,6 +1070,8 @@
                this->setCursor(Qt::BlankCursor);
        }
 
+       qDebug() << "QKeyEvent ev:" << ev;
+
        const QString inp = Input::convertKey(ev->text(), ev->key(), ev->modifiers());
        if (inp.isEmpty()) {
                QWidget::keyPressEvent(ev);
```

For Windows, the output must be written to a file: https://github.com/equalsraf/neovim-qt/wiki#i-cant-see-debug-messages-in-windows

**Comment by jgehrig** [comment] 2019-12-28 06:04
Please correct me if I am wrong with any assumptions...

The request is to make the MacOS special key entry work. For example with my U.S. keyboard layout, I can type `Alt + a` to insert the character `å`.

From what I can tell, the issue is key events are sent with AltModifier `<M-...>`. In my example, `<M-å>`. You can observe this with a `qDebug()` statement or `Ctrl + V` `Alt + a`; both show the input `<M-å>`being sent.

This can be fixed with simple patch:
```patch
diff --git a/src/gui/input.cpp b/src/gui/input.cpp
index d6dfe39..c7dced2 100644
--- a/src/gui/input.cpp
+++ b/src/gui/input.cpp
@@ -199,7 +199,8 @@ QString convertKey(const QString& text, int key, Qt::KeyboardModifiers mod) noex
 
        // Remove Shift
        if (c.unicode() >= 0x80 || (!c.isLetterOrNumber() && c.isPrint())) {
-               mod &= ~Qt::ShiftModifier;
+               mod &= ~Qt::KeyboardModifier::ShiftModifier;
+               mod &= ~Qt::KeyboardModifier::AltModifier; // FIXME MacOS Specific?
        }
 
        // Remove Ctrl empty characters at the start of the ASCII range
```

Although, a real solution may require more work to avoid impacting non-MacOS platforms.

Unfortunately, the requests of @ravicious and @zgpio are in direct conflict. From my example, we cannot map `<M-a>` and allow `å` input at the same time. These are identical key events.

We might be able to work around the issue by making ravicious' scenario work by default. For zgpio's request, I suspect I can write code that sends `<M-a>`-type events if keyboard layout `Unicode Hex Input` is used.

**Comment by Iazel** [comment] 2020-02-01 09:59
Hi, I'm having a similar problem, when I press "AltGr+<something>" it will first print a weird symbol and then print the desired character. The weird symbol is printed as soon as I press the AltGr and even if I just press that alone, so to me looks like this button is not handled as an actual modifier key.

I'm using Debian 9 (stretch) and compiled neovim-qt from current master.

Debug output:
```
QKeyEvent ev: QKeyEvent(KeyPress, Key_AltGr, GroupSwitchModifier)
   "ᄃ"
QKeyEvent ev: QKeyEvent(KeyPress, Key_AsciiTilde, GroupSwitchModifier, text="~")
   "~"
```
I'm using the Italian keyboard layout, so for me tilde is `AltGr+ì` where `ì` is the button to the left of backspace.

**Comment by jgehrig** [comment] 2020-02-01 12:53
@lazel

Thanks for the bug report and debugging work!

That patch looks reasonable to me. The only other thing it needs is a test case. You are welcome to write a Pull Request for this. If not, I can put something together in a day or two.

**Comment by jgehrig** [comment] 2020-07-31 04:47
Works in the latest release `v0.2.16`.

Marking as closed.

**Closed by jgehrig** 2020-07-31 04:47 UTC
