### ISSUE TITLE
Redrawing screen does not work as expected

### ISSUE THREAD

**Issue by przepompownia** [equalsraf/neovim-qt#1028] opened 2022-11-13 16:08 UTC
Using the recent nvim (736c36c02) and neovim-qt (409fad8) I have numerous problems with redrawing content (for a couple of weeks). Most of them would require some time to prepare a good example. I found an example that is not the best but can be a suggestion:

https://user-images.githubusercontent.com/11404453/201530893-a35f9c46-cf60-4e69-8e1d-dfe53b6fc971.mp4

It was run with `nvim-qt --nvim ~/tmp/nvim-from-src/bin/nvim -- -u NONE`. Only `Ctrl-L` (0:23 on the screencast) can set background color to the whole window. 

Tested on Wayland (fresh Debian Sid, gnome-shell 43.1).

**Comment by sid-6581** [comment] 2022-11-13 20:45
I've had similar redrawing problems lately, on Windows. Resizing the window forces a redraw.

**Comment by jgehrig** [comment] 2022-11-14 15:40
This looks like it could be a duplicate of #993 and #1011. Can you quickly test those scenarios too?

This could be fixed by #1021, it is worth trying to manually enable `ext_linegrid` and seeing if this still reproduces. See those bugs for details.

If this is also related to the lack of `ext_linegrid`, I have not determined the root cause. I don't see any obvious mishandling of the render calls sent by Neovim. I'm not sure if this is an issue with `nvim` or `nvim-qt` yet... In any event, using the new rendering protocol resolves the background color issues.

I should have merged that PR already, but life has been busy! :grimacing:

**Comment by jgehrig** [comment] 2022-11-14 16:31
@sid-6581 

Thanks for the info! So to clarify -- You have `ext_linegrid` enabled on Windows, and you still see the issues describe here?

Assuming yes. I will take some time to investigate soon and report back.

**Comment by przepompownia** [comment] 2022-11-14 16:47
> This looks like it could be a duplicate of #993 and #1011. Can you quickly test those scenarios too?
> 

@jgehrig good to know that there is some solution. I made screencasts into #993 and I'm going to try it for my regular job with checking if it will fix the problem of outdated text too. The later problem made nvim-qt unusable for me (the content of buffer was refreshed after (for example) switching to another window and going back) in Wayland but it was hard to reproduce (in opposite to this small issue).

**Comment by jgehrig** [comment] 2022-11-14 16:55
>  The later problem made nvim-qt unusable for me (the content of buffer was refreshed after (for example) switching to another window and going back) in Wayland but it was hard to reproduce (in opposite to this small issue).

This seems like a high-priority issue...

If there is something that makes `nvim-qt` unusable for you, I'll prioritize an investigation and fix. Let me know if the bad issue is not fixed by the ext_linegrid toggle.

If the set of steps is clear, an inconsistent repro is fine with me. If that doesn't work, we could also work to add logging to a Debug build. Logging could help us track down the inconsistent issue, if you're willing to provide them.

**Comment by przepompownia** [comment] 2022-11-14 18:01
Just for the sake of this issue, the initial case seems to be fixed on `jg-underline`:

https://user-images.githubusercontent.com/11404453/201732346-eb7142a2-630a-44d0-ac34-58c55fdc10ca.mp4

@jgehrig thanks for showing interest and let me take time to observe what happens in my regular environment.

**Comment by przepompownia** [comment] 2022-11-16 00:28
After on day of regular work I did not notice any outdated contents. Compared to previous frequent issues it's probable that `ext_linegrid` solves the problem and I can use neovim-qt again!

**Comment by jgehrig** [comment] 2022-11-18 21:12
I'm glad to hear that!

I've merged #1021, so I'm going to mark this issue as closed. If you do continue to see issues, please let me know and we will get the problems resolved.

**Closed by jgehrig** 2022-11-18 21:12 UTC
