### ISSUE TITLE
Fonts are blurred on HiDPI displays

### ISSUE THREAD

**Issue by johanhelsing** [equalsraf/neovim-qt#39] opened 2015-09-09 08:16 UTC
Example:
![screenshot from 2015-09-09 10-15-46](https://cloud.githubusercontent.com/assets/2620557/9756597/c080cad0-56db-11e5-818b-f5268ebb4b2c.png)

**Comment by equalsraf** [comment] 2015-09-11 18:22
Hi @johanhelsing. I don't have a HDPI display to test with, but lets try and narrow it down. Does this also happen with other Qt apps? What version of Qt are you running and in what system?

Does setting the environment variable QT_DEVICE_PIXEL_RATIO=2 help at all? or QT_DEVICE_PIXEL_RATIO=AUTO.

There are bug reports in Qt apps for similar issues around HDPI ([here](http://www.itopen.it/qgis-and-qt-getting-ready-for-hidpi-screens/) or in [QtCreator1](https://bugreports.qt.io/browse/QTCREATORBUG-13578) and [here](https://bugreports.qt.io/browse/QTCREATORBUG-14283)). I don't think we are doing anything wrong on our side (e.g. we set font size in points no in pixels).

**Comment by johanhelsing** [comment] 2015-09-12 13:44
Hi, I just tested. I already had QT_DEVICE_PIXEL_RATIO set to 2... So I tried with 1. And the issue went away!
![screenshot from 2015-09-12 15-39-34](https://cloud.githubusercontent.com/assets/2620557/9831787/87eb21ee-5964-11e5-8ba1-8b28184dc5a2.png)

Looks exactly the same, but the font is not blurred anymore. Not sure why this happens. I develop Qt apps myself and I don't have that problem.

How are you rendering the glyphs/text? Could you point me to the right point in the source code, and I could try some experiments.

Don't have the time to look at the issues you linked to right now.

Btw, you shouldn't you be able to test and see the issues for yourself with that environment variable? Does it look good on your machine?

**Comment by equalsraf** [comment] 2015-09-12 21:27
> Btw, shouldn't you be able to test and see the issues for yourself with that environment variable? Does it look good on your machine?

Good call, confirmed QT_DEVICE_PIXEL_RATIO=2 breaks it for me. Text is rendered in [handlePut()](https://github.com/equalsraf/neovim-qt/blob/cf911aecdb920341b4290c4221db6dbb9e2f3578/src/gui/shell.cpp#L252).

![bug1](https://cloud.githubusercontent.com/assets/715238/9833772/f5f0f956-599c-11e5-97d9-8d74596812e0.png)

**Comment by equalsraf** [comment] 2015-09-12 22:50
Maybe its related to the QImage copies going around when painting the widget, the Shell/QWidget reports devicePixelRatio = 2, while QImage.devicePixelRatio = 1

**Comment by equalsraf** [comment] 2016-03-14 19:33
This seems to be fixed in #109. The left one is 0.1.1, the right one is #109. Can anyone with an actual HiDPI screen confirm? Here is a [build](https://ci.appveyor.com/project/equalsraf/neovim-qt/build/601/job/tmqij2rp7kiywjis/artifacts).

![capture](https://cloud.githubusercontent.com/assets/715238/13757225/5c0865e4-ea1b-11e5-9b01-63ae2631b1c4.PNG)

**Comment by equalsraf** [comment] 2016-03-31 17:34
Fixed in master.

**Closed by equalsraf** 2016-03-31 17:34 UTC
