### ISSUE TITLE
Popup menu flickering when using GuiPopupmenu 0 in combination with lazyredraw

### ISSUE THREAD

**Issue by YorickPeterse** [equalsraf/neovim-qt#530] opened 2019-03-28 14:06 UTC
When using NeoVim's own popup menu (`GuiPopupmenu 0`), I am noticing quite a bit of flickering when tabbing through the listed items. This is not happening when using NeoVim's TUI.

Here is what it looks like when using the TUI:

https://gfycat.com/KaleidoscopicCheapKob

Here is what it looks like when using nvim-qt:

https://gfycat.com/ThatRectangularFoxterrier

Reproducing this is probably a bit tricky, unfortunately. Using my dotfiles (https://gitlab.com/yorickpeterse/dotfiles) I can reproduce it even with simple files, such as this one:

```ruby
aafooooooooooooooooo1 = 2
aafooooooooooooooooo2 = 2
aafooooooooooooooooo3 = 2
aafooooooooooooooooo4 = 2
aafooooooooooooooooo5 = 2
aafooooooooooooooooo6 = 2
aaa = 1
aab = 1
aac = 1
aad = 1
aae = 1
aaf = 1
aag = 1
aah = 1
aai = 1
aaj = 1
aak = 1
aal = 1
aam = 1
aan = 1
aao = 1
aap = 1
aaq = 1
aar = 1
aas = 1
aat = 1
aau = 1
aav = 1
```

To reproduce it, move the cursor to the end of the file, then type `aa` and wait for the popup menu to appear. If you then press and hold tab (or just tab manually), you should see quite a lot of flickering. I tried reproducing this using `nvim-qt -u NONE`, but it doesn't happen there (at least that I can tell). I suspect that the amount of syntax highlighting might have an impact on the flickering.

**Comment by YorickPeterse** [comment] 2019-03-28 14:22
Here is a minimal way of reproducing it:

First, create `/tmp/minimal.vim` and add the following:

```vim
set completeopt=menu
set lz
set omnifunc=syntaxcomplete#Complete
set pumheight=50
set relativenumber
set termguicolors

filetype plugin indent on
syntax on
```

Then create `/tmp/example.rb` and add the following to it:

```ruby
mrfooooooooooooooooo1 = 2
mrfooooooooooooooooo2 = 2
mrfooooooooooooooooo3 = 2
mrfooooooooooooooooo4 = 2
mrfooooooooooooooooo5 = 2
mrfooooooooooooooooo6 = 2
mrforooooooooooooooo1 = 2
mrforooooooooooooooo2 = 2
mrforooooooooooooooo3 = 2
mrforooooooooooooooo4 = 2
mrforooooooooooooooo5 = 2
mrforooooooooooooooo6 = 2
mrfobooooooooooooooo1 = 2
mrfobooooooooooooooo2 = 2
mrfobooooooooooooooo3 = 2
mrfobooooooooooooooo4 = 2
mrfobooooooooooooooo5 = 2
mrfobooooooooooooooo6 = 2
mrfoooooooooooaooooo1 = 2
mrfoooooooooooaooooo2 = 2
mrfoooooooooooaooooo3 = 2
mrfoooooooooooaooooo4 = 2
mrfoooooooooooaooooo5 = 2
mrfoooooooooooaooooo6 = 2
mrforoooooooooaooooo1 = 2
mrforoooooooooaooooo2 = 2
mrforoooooooooaooooo3 = 2
mrforoooooooooaooooo4 = 2
mrforoooooooooaooooo5 = 2
mrforoooooooooaooooo6 = 2
mrfoboooooooooaooooo1 = 2
mrfoboooooooooaooooo2 = 2
mrfoboooooooooaooooo3 = 2
mrfoboooooooooaooooo4 = 2
mrfoboooooooooaooooo5 = 2
mrfoboooooooooaooooo6 = 2

mr = Struct.new(:iid, :target_branch, :web_url)

mr1 = mr.new(1, 'foo', 'https://example.com/merge_requests/1')
mr2 = mr.new(2, 'foo', 'https://example.com/merge_requests/2')
mr3 = mr.new(3, 'bar', 'https://example.com/merge_requests/3')

Slack::ChatopsNotification.merged_security_merge_requests(result)
```

Then start nvim-qt as follows:

    nvim-qt -- -u /tmp/minimal.vim /tmp/example.rb

Now move the cursor to the line below `mr3 = ...`, type `mr` and hit Ctrl-p to trigger keyword completion. If you then use Ctrl-n to navigate down the list you'll see _a lot_ of flickering.

Disabling lazy redraw removes the flickering, though in the TUI this isn't necessary in the first place.

**Comment by jgehrig** [comment] 2019-07-07 03:00
I took a look at this... I haven't been able to find a root cause yet :/

A few observations:
- This issue still exists when everything is drawn via `ext_linegrid`.
- The order of RPC draw events/content is identical between repro and non-repro cases. Timing issue?
- Performance profiling of the scenario hasn't yielded any obvious bottlenecks, both cases look similar.
- Option `relativenumber` exacerbates the problem. Without this option set, only the 1st entry flickers.

An even-more-sparse `/tmp/minimal.vim`:
```
set lz
set pumheight=50
set relativenumber
```

Here is a good does-not-reproduce comparison, `/tmp/norepro.vim`:
```
set pumheight=50
set relativenumber
```

**Comment by jgehrig** [comment] 2020-03-02 07:19
Interesting... It looks like this issue was fixed in a recent release of neovim!

`<=neovim-0.3.8`: YES-REPRO
`>=neovim-0.4.0`: NO-REPRO

**Comment by jgehrig** [comment] 2020-09-01 05:18
It looks like this was a server-side `neovim` issue.

Tested with neovim-qt `v0.2.16` and neovim `v0.4.3`. Marking as closed.

**Closed by jgehrig** 2020-09-01 05:18 UTC
