### ISSUE TITLE
When a swap file exists, nvim-qt fails to prompt anything

### ISSUE THREAD

**Issue by yhylord** [equalsraf/neovim-qt#144] opened 2016-06-16 06:37 UTC
How to reproduce:
1. Open a file, e.g. `b.cpp`, in neovim-qt
2. Run `nvim-qt -- b.cpp` again.

The second window of neovim-qt will show nothing.

**Comment by equalsraf** [comment] 2016-06-16 08:05
This sounds like a duplicate of #78, it needs to fixed upstream.

**Closed** 2017-09-20 22:36 UTC
